// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/cloth/harvest/application/ports.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/cloth/harvest/application/ports.go -destination services/api/internal/cloth/harvest/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/cloth/harvest/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(arg0 context.Context, arg1 domain.Harvest, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), arg0, arg1, arg2, arg3)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Harvest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockRepository) Find(arg0 context.Context, arg1 string) (domain.Harvest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Harvest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), arg0, arg1)
}

// FindByCommand mocks base method.
func (m *MockRepository) FindByCommand(arg0 context.Context, arg1 string) (domain.Harvest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommand", arg0, arg1)
	ret0, _ := ret[0].(domain.Harvest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommand indicates an expected call of FindByCommand.
func (mr *MockRepositoryMockRecorder) FindByCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommand", reflect.TypeOf((*MockRepository)(nil).FindByCommand), arg0, arg1)
}

// FindByHandoff mocks base method.
func (m *MockRepository) FindByHandoff(arg0 context.Context, arg1 string) (domain.Harvest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHandoff", arg0, arg1)
	ret0, _ := ret[0].(domain.Harvest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHandoff indicates an expected call of FindByHandoff.
func (mr *MockRepositoryMockRecorder) FindByHandoff(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHandoff", reflect.TypeOf((*MockRepository)(nil).FindByHandoff), arg0, arg1)
}

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
	isgomock struct{}
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// Require mocks base method.
func (m *MockAuthorizer) Require(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Require", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Require indicates an expected call of Require.
func (mr *MockAuthorizerMockRecorder) Require(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Require", reflect.TypeOf((*MockAuthorizer)(nil).Require), arg0, arg1, arg2, arg3)
}

// MockPairPolicy is a mock of PairPolicy interface.
type MockPairPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockPairPolicyMockRecorder
	isgomock struct{}
}

// MockPairPolicyMockRecorder is the mock recorder for MockPairPolicy.
type MockPairPolicyMockRecorder struct {
	mock *MockPairPolicy
}

// NewMockPairPolicy creates a new mock instance.
func NewMockPairPolicy(ctrl *gomock.Controller) *MockPairPolicy {
	mock := &MockPairPolicy{ctrl: ctrl}
	mock.recorder = &MockPairPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPairPolicy) EXPECT() *MockPairPolicyMockRecorder {
	return m.recorder
}

// Revalidate mocks base method.
func (m *MockPairPolicy) Revalidate(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revalidate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revalidate indicates an expected call of Revalidate.
func (mr *MockPairPolicyMockRecorder) Revalidate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revalidate", reflect.TypeOf((*MockPairPolicy)(nil).Revalidate), arg0, arg1, arg2)
}

// MockOwnership is a mock of Ownership interface.
type MockOwnership struct {
	ctrl     *gomock.Controller
	recorder *MockOwnershipMockRecorder
	isgomock struct{}
}

// MockOwnershipMockRecorder is the mock recorder for MockOwnership.
type MockOwnershipMockRecorder struct {
	mock *MockOwnership
}

// NewMockOwnership creates a new mock instance.
func NewMockOwnership(ctrl *gomock.Controller) *MockOwnership {
	mock := &MockOwnership{ctrl: ctrl}
	mock.recorder = &MockOwnershipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnership) EXPECT() *MockOwnershipMockRecorder {
	return m.recorder
}

// Revalidate mocks base method.
func (m *MockOwnership) Revalidate(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revalidate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revalidate indicates an expected call of Revalidate.
func (mr *MockOwnershipMockRecorder) Revalidate(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revalidate", reflect.TypeOf((*MockOwnership)(nil).Revalidate), arg0, arg1, arg2, arg3)
}

// MockRecipeValidator is a mock of RecipeValidator interface.
type MockRecipeValidator struct {
	ctrl     *gomock.Controller
	recorder *MockRecipeValidatorMockRecorder
	isgomock struct{}
}

// MockRecipeValidatorMockRecorder is the mock recorder for MockRecipeValidator.
type MockRecipeValidatorMockRecorder struct {
	mock *MockRecipeValidator
}

// NewMockRecipeValidator creates a new mock instance.
func NewMockRecipeValidator(ctrl *gomock.Controller) *MockRecipeValidator {
	mock := &MockRecipeValidator{ctrl: ctrl}
	mock.recorder = &MockRecipeValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipeValidator) EXPECT() *MockRecipeValidatorMockRecorder {
	return m.recorder
}

// Revalidate mocks base method.
func (m *MockRecipeValidator) Revalidate(arg0 context.Context, arg1 domain.Payload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revalidate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revalidate indicates an expected call of Revalidate.
func (mr *MockRecipeValidatorMockRecorder) Revalidate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revalidate", reflect.TypeOf((*MockRecipeValidator)(nil).Revalidate), arg0, arg1)
}

// MockProviderAuth is a mock of ProviderAuth interface.
type MockProviderAuth struct {
	ctrl     *gomock.Controller
	recorder *MockProviderAuthMockRecorder
	isgomock struct{}
}

// MockProviderAuthMockRecorder is the mock recorder for MockProviderAuth.
type MockProviderAuthMockRecorder struct {
	mock *MockProviderAuth
}

// NewMockProviderAuth creates a new mock instance.
func NewMockProviderAuth(ctrl *gomock.Controller) *MockProviderAuth {
	mock := &MockProviderAuth{ctrl: ctrl}
	mock.recorder = &MockProviderAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderAuth) EXPECT() *MockProviderAuthMockRecorder {
	return m.recorder
}

// Require mocks base method.
func (m *MockProviderAuth) Require(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Require", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Require indicates an expected call of Require.
func (mr *MockProviderAuthMockRecorder) Require(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Require", reflect.TypeOf((*MockProviderAuth)(nil).Require), arg0, arg1, arg2)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
