// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/analytics/retention/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyCatalog is a mock of PolicyCatalog interface.
type MockPolicyCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyCatalogMockRecorder
	isgomock struct{}
}

// MockPolicyCatalogMockRecorder is the mock recorder for MockPolicyCatalog.
type MockPolicyCatalogMockRecorder struct {
	mock *MockPolicyCatalog
}

// NewMockPolicyCatalog creates a new mock instance.
func NewMockPolicyCatalog(ctrl *gomock.Controller) *MockPolicyCatalog {
	mock := &MockPolicyCatalog{ctrl: ctrl}
	mock.recorder = &MockPolicyCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyCatalog) EXPECT() *MockPolicyCatalogMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockPolicyCatalog) Current(arg0 context.Context) (domain.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", arg0)
	ret0, _ := ret[0].(domain.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockPolicyCatalogMockRecorder) Current(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockPolicyCatalog)(nil).Current), arg0)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AggregateErase mocks base method.
func (m *MockStore) AggregateErase(arg0 context.Context, arg1 domain.Candidate, arg2 domain.Decision, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateErase", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AggregateErase indicates an expected call of AggregateErase.
func (mr *MockStoreMockRecorder) AggregateErase(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateErase", reflect.TypeOf((*MockStore)(nil).AggregateErase), arg0, arg1, arg2, arg3)
}

// ClaimDue mocks base method.
func (m *MockStore) ClaimDue(arg0 context.Context, arg1 time.Time, arg2 int, arg3 string, arg4 time.Time) ([]domain.Candidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDue", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]domain.Candidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDue indicates an expected call of ClaimDue.
func (mr *MockStoreMockRecorder) ClaimDue(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDue", reflect.TypeOf((*MockStore)(nil).ClaimDue), arg0, arg1, arg2, arg3, arg4)
}

// Pseudonymize mocks base method.
func (m *MockStore) Pseudonymize(arg0 context.Context, arg1 domain.Candidate, arg2 domain.Decision, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pseudonymize", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pseudonymize indicates an expected call of Pseudonymize.
func (mr *MockStoreMockRecorder) Pseudonymize(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pseudonymize", reflect.TypeOf((*MockStore)(nil).Pseudonymize), arg0, arg1, arg2, arg3, arg4)
}

// MockPseudonymizer is a mock of Pseudonymizer interface.
type MockPseudonymizer struct {
	ctrl     *gomock.Controller
	recorder *MockPseudonymizerMockRecorder
	isgomock struct{}
}

// MockPseudonymizerMockRecorder is the mock recorder for MockPseudonymizer.
type MockPseudonymizerMockRecorder struct {
	mock *MockPseudonymizer
}

// NewMockPseudonymizer creates a new mock instance.
func NewMockPseudonymizer(ctrl *gomock.Controller) *MockPseudonymizer {
	mock := &MockPseudonymizer{ctrl: ctrl}
	mock.recorder = &MockPseudonymizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPseudonymizer) EXPECT() *MockPseudonymizerMockRecorder {
	return m.recorder
}

// Derive mocks base method.
func (m *MockPseudonymizer) Derive(arg0 string, arg1 uint64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Derive", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Derive indicates an expected call of Derive.
func (mr *MockPseudonymizerMockRecorder) Derive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Derive", reflect.TypeOf((*MockPseudonymizer)(nil).Derive), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
