// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/seed/source/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(arg0 context.Context, arg1 domain.Request, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), arg0, arg1, arg2, arg3)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockRepository) Find(arg0 context.Context, arg1 string) (domain.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), arg0, arg1)
}

// FindByCommand mocks base method.
func (m *MockRepository) FindByCommand(arg0 context.Context, arg1 string) (domain.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommand", arg0, arg1)
	ret0, _ := ret[0].(domain.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommand indicates an expected call of FindByCommand.
func (mr *MockRepositoryMockRecorder) FindByCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommand", reflect.TypeOf((*MockRepository)(nil).FindByCommand), arg0, arg1)
}

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
	isgomock struct{}
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// Require mocks base method.
func (m *MockAuthorizer) Require(arg0 context.Context, arg1, arg2 string, arg3 domain.SourceType, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Require", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Require indicates an expected call of Require.
func (mr *MockAuthorizerMockRecorder) Require(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Require", reflect.TypeOf((*MockAuthorizer)(nil).Require), arg0, arg1, arg2, arg3, arg4)
}

// MockSourcePolicy is a mock of SourcePolicy interface.
type MockSourcePolicy struct {
	ctrl     *gomock.Controller
	recorder *MockSourcePolicyMockRecorder
	isgomock struct{}
}

// MockSourcePolicyMockRecorder is the mock recorder for MockSourcePolicy.
type MockSourcePolicyMockRecorder struct {
	mock *MockSourcePolicy
}

// NewMockSourcePolicy creates a new mock instance.
func NewMockSourcePolicy(ctrl *gomock.Controller) *MockSourcePolicy {
	mock := &MockSourcePolicy{ctrl: ctrl}
	mock.recorder = &MockSourcePolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourcePolicy) EXPECT() *MockSourcePolicyMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockSourcePolicy) Allow(arg0 context.Context, arg1 domain.SourceType, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockSourcePolicyMockRecorder) Allow(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockSourcePolicy)(nil).Allow), arg0, arg1, arg2)
}

// MockCandidateResolver is a mock of CandidateResolver interface.
type MockCandidateResolver struct {
	ctrl     *gomock.Controller
	recorder *MockCandidateResolverMockRecorder
	isgomock struct{}
}

// MockCandidateResolverMockRecorder is the mock recorder for MockCandidateResolver.
type MockCandidateResolverMockRecorder struct {
	mock *MockCandidateResolver
}

// NewMockCandidateResolver creates a new mock instance.
func NewMockCandidateResolver(ctrl *gomock.Controller) *MockCandidateResolver {
	mock := &MockCandidateResolver{ctrl: ctrl}
	mock.recorder = &MockCandidateResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCandidateResolver) EXPECT() *MockCandidateResolverMockRecorder {
	return m.recorder
}

// CandidateIDs mocks base method.
func (m *MockCandidateResolver) CandidateIDs(arg0 context.Context, arg1 domain.SourceType, arg2 string, arg3 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CandidateIDs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CandidateIDs indicates an expected call of CandidateIDs.
func (mr *MockCandidateResolverMockRecorder) CandidateIDs(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CandidateIDs", reflect.TypeOf((*MockCandidateResolver)(nil).CandidateIDs), arg0, arg1, arg2, arg3)
}

// MockConsentVisibility is a mock of ConsentVisibility interface.
type MockConsentVisibility struct {
	ctrl     *gomock.Controller
	recorder *MockConsentVisibilityMockRecorder
	isgomock struct{}
}

// MockConsentVisibilityMockRecorder is the mock recorder for MockConsentVisibility.
type MockConsentVisibilityMockRecorder struct {
	mock *MockConsentVisibility
}

// NewMockConsentVisibility creates a new mock instance.
func NewMockConsentVisibility(ctrl *gomock.Controller) *MockConsentVisibility {
	mock := &MockConsentVisibility{ctrl: ctrl}
	mock.recorder = &MockConsentVisibilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentVisibility) EXPECT() *MockConsentVisibilityMockRecorder {
	return m.recorder
}

// Visible mocks base method.
func (m *MockConsentVisibility) Visible(arg0 context.Context, arg1, arg2 string, arg3 domain.SourceType, arg4 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Visible", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Visible indicates an expected call of Visible.
func (mr *MockConsentVisibilityMockRecorder) Visible(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Visible", reflect.TypeOf((*MockConsentVisibility)(nil).Visible), arg0, arg1, arg2, arg3, arg4)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(namespace, value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", namespace, value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(namespace, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), namespace, value)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
