// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/launch/readiness/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthority is a mock of Authority interface.
type MockAuthority struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorityMockRecorder
	isgomock struct{}
}

// MockAuthorityMockRecorder is the mock recorder for MockAuthority.
type MockAuthorityMockRecorder struct {
	mock *MockAuthority
}

// NewMockAuthority creates a new mock instance.
func NewMockAuthority(ctrl *gomock.Controller) *MockAuthority {
	mock := &MockAuthority{ctrl: ctrl}
	mock.recorder = &MockAuthorityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthority) EXPECT() *MockAuthorityMockRecorder {
	return m.recorder
}

// RequireLaunchReviewer mocks base method.
func (m *MockAuthority) RequireLaunchReviewer(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireLaunchReviewer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireLaunchReviewer indicates an expected call of RequireLaunchReviewer.
func (mr *MockAuthorityMockRecorder) RequireLaunchReviewer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireLaunchReviewer", reflect.TypeOf((*MockAuthority)(nil).RequireLaunchReviewer), arg0, arg1)
}

// MockFamilyProjection is a mock of FamilyProjection interface.
type MockFamilyProjection struct {
	ctrl     *gomock.Controller
	recorder *MockFamilyProjectionMockRecorder
	isgomock struct{}
}

// MockFamilyProjectionMockRecorder is the mock recorder for MockFamilyProjection.
type MockFamilyProjectionMockRecorder struct {
	mock *MockFamilyProjection
}

// NewMockFamilyProjection creates a new mock instance.
func NewMockFamilyProjection(ctrl *gomock.Controller) *MockFamilyProjection {
	mock := &MockFamilyProjection{ctrl: ctrl}
	mock.recorder = &MockFamilyProjectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFamilyProjection) EXPECT() *MockFamilyProjectionMockRecorder {
	return m.recorder
}

// CurrentFamilyDensity mocks base method.
func (m *MockFamilyProjection) CurrentFamilyDensity(arg0 context.Context, arg1 string) (domain.FamilyDensity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentFamilyDensity", arg0, arg1)
	ret0, _ := ret[0].(domain.FamilyDensity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentFamilyDensity indicates an expected call of CurrentFamilyDensity.
func (mr *MockFamilyProjectionMockRecorder) CurrentFamilyDensity(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentFamilyDensity", reflect.TypeOf((*MockFamilyProjection)(nil).CurrentFamilyDensity), arg0, arg1)
}

// MockHostProjection is a mock of HostProjection interface.
type MockHostProjection struct {
	ctrl     *gomock.Controller
	recorder *MockHostProjectionMockRecorder
	isgomock struct{}
}

// MockHostProjectionMockRecorder is the mock recorder for MockHostProjection.
type MockHostProjectionMockRecorder struct {
	mock *MockHostProjection
}

// NewMockHostProjection creates a new mock instance.
func NewMockHostProjection(ctrl *gomock.Controller) *MockHostProjection {
	mock := &MockHostProjection{ctrl: ctrl}
	mock.recorder = &MockHostProjectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostProjection) EXPECT() *MockHostProjectionMockRecorder {
	return m.recorder
}

// CurrentHostCoverage mocks base method.
func (m *MockHostProjection) CurrentHostCoverage(arg0 context.Context, arg1 string) (domain.HostCoverage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentHostCoverage", arg0, arg1)
	ret0, _ := ret[0].(domain.HostCoverage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentHostCoverage indicates an expected call of CurrentHostCoverage.
func (mr *MockHostProjectionMockRecorder) CurrentHostCoverage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentHostCoverage", reflect.TypeOf((*MockHostProjection)(nil).CurrentHostCoverage), arg0, arg1)
}

// MockLicenseProjection is a mock of LicenseProjection interface.
type MockLicenseProjection struct {
	ctrl     *gomock.Controller
	recorder *MockLicenseProjectionMockRecorder
	isgomock struct{}
}

// MockLicenseProjectionMockRecorder is the mock recorder for MockLicenseProjection.
type MockLicenseProjectionMockRecorder struct {
	mock *MockLicenseProjection
}

// NewMockLicenseProjection creates a new mock instance.
func NewMockLicenseProjection(ctrl *gomock.Controller) *MockLicenseProjection {
	mock := &MockLicenseProjection{ctrl: ctrl}
	mock.recorder = &MockLicenseProjectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLicenseProjection) EXPECT() *MockLicenseProjectionMockRecorder {
	return m.recorder
}

// CurrentLicenseCoverage mocks base method.
func (m *MockLicenseProjection) CurrentLicenseCoverage(arg0 context.Context, arg1, arg2 string) (domain.LicenseCoverage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentLicenseCoverage", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.LicenseCoverage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentLicenseCoverage indicates an expected call of CurrentLicenseCoverage.
func (mr *MockLicenseProjectionMockRecorder) CurrentLicenseCoverage(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentLicenseCoverage", reflect.TypeOf((*MockLicenseProjection)(nil).CurrentLicenseCoverage), arg0, arg1, arg2)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockRepository) Find(arg0 context.Context, arg1 string) (domain.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
