// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AccessEvidence mocks base method.
func (m *MockRepository) AccessEvidence(arg0 context.Context, arg1 EvidenceAccess) (Evidence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessEvidence", arg0, arg1)
	ret0, _ := ret[0].(Evidence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessEvidence indicates an expected call of AccessEvidence.
func (mr *MockRepositoryMockRecorder) AccessEvidence(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessEvidence", reflect.TypeOf((*MockRepository)(nil).AccessEvidence), arg0, arg1)
}

// Decide mocks base method.
func (m *MockRepository) Decide(arg0 context.Context, arg1 DecisionCommand) (DecisionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decide", arg0, arg1)
	ret0, _ := ret[0].(DecisionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decide indicates an expected call of Decide.
func (mr *MockRepositoryMockRecorder) Decide(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decide", reflect.TypeOf((*MockRepository)(nil).Decide), arg0, arg1)
}

// Detail mocks base method.
func (m *MockRepository) Detail(arg0 context.Context, arg1 string) (CaseDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", arg0, arg1)
	ret0, _ := ret[0].(CaseDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockRepositoryMockRecorder) Detail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockRepository)(nil).Detail), arg0, arg1)
}

// ListQueued mocks base method.
func (m *MockRepository) ListQueued(arg0 context.Context, arg1 int) ([]CaseSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQueued", arg0, arg1)
	ret0, _ := ret[0].([]CaseSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQueued indicates an expected call of ListQueued.
func (mr *MockRepositoryMockRecorder) ListQueued(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQueued", reflect.TypeOf((*MockRepository)(nil).ListQueued), arg0, arg1)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(namespace, value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", namespace, value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(namespace, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), namespace, value)
}
