// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/notifications/application/notifications.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/notifications/application/notifications.go -destination services/api/internal/notifications/application/mock_notifications_test.go -package application PreferencesRepository,DeliveryCounter
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/notifications/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPreferencesRepository is a mock of PreferencesRepository interface.
type MockPreferencesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPreferencesRepositoryMockRecorder
	isgomock struct{}
}

// MockPreferencesRepositoryMockRecorder is the mock recorder for MockPreferencesRepository.
type MockPreferencesRepositoryMockRecorder struct {
	mock *MockPreferencesRepository
}

// NewMockPreferencesRepository creates a new mock instance.
func NewMockPreferencesRepository(ctrl *gomock.Controller) *MockPreferencesRepository {
	mock := &MockPreferencesRepository{ctrl: ctrl}
	mock.recorder = &MockPreferencesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreferencesRepository) EXPECT() *MockPreferencesRepositoryMockRecorder {
	return m.recorder
}

// FindByMember mocks base method.
func (m *MockPreferencesRepository) FindByMember(arg0 context.Context, arg1 string) (domain.Preferences, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByMember", arg0, arg1)
	ret0, _ := ret[0].(domain.Preferences)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByMember indicates an expected call of FindByMember.
func (mr *MockPreferencesRepositoryMockRecorder) FindByMember(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByMember", reflect.TypeOf((*MockPreferencesRepository)(nil).FindByMember), arg0, arg1)
}

// Upsert mocks base method.
func (m *MockPreferencesRepository) Upsert(arg0 context.Context, arg1 domain.Preferences) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPreferencesRepositoryMockRecorder) Upsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPreferencesRepository)(nil).Upsert), arg0, arg1)
}

// MockDeliveryCounter is a mock of DeliveryCounter interface.
type MockDeliveryCounter struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryCounterMockRecorder
	isgomock struct{}
}

// MockDeliveryCounterMockRecorder is the mock recorder for MockDeliveryCounter.
type MockDeliveryCounterMockRecorder struct {
	mock *MockDeliveryCounter
}

// NewMockDeliveryCounter creates a new mock instance.
func NewMockDeliveryCounter(ctrl *gomock.Controller) *MockDeliveryCounter {
	mock := &MockDeliveryCounter{ctrl: ctrl}
	mock.recorder = &MockDeliveryCounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryCounter) EXPECT() *MockDeliveryCounterMockRecorder {
	return m.recorder
}

// ClaimSlot mocks base method.
func (m *MockDeliveryCounter) ClaimSlot(ctx context.Context, memberID, localDate string, cap int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSlot", ctx, memberID, localDate, cap)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimSlot indicates an expected call of ClaimSlot.
func (mr *MockDeliveryCounterMockRecorder) ClaimSlot(ctx, memberID, localDate, cap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSlot", reflect.TypeOf((*MockDeliveryCounter)(nil).ClaimSlot), ctx, memberID, localDate, cap)
}
