// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/ai/gateway/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConsentGate is a mock of ConsentGate interface.
type MockConsentGate struct {
	ctrl     *gomock.Controller
	recorder *MockConsentGateMockRecorder
	isgomock struct{}
}

// MockConsentGateMockRecorder is the mock recorder for MockConsentGate.
type MockConsentGateMockRecorder struct {
	mock *MockConsentGate
}

// NewMockConsentGate creates a new mock instance.
func NewMockConsentGate(ctrl *gomock.Controller) *MockConsentGate {
	mock := &MockConsentGate{ctrl: ctrl}
	mock.recorder = &MockConsentGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentGate) EXPECT() *MockConsentGateMockRecorder {
	return m.recorder
}

// RequireCurrent mocks base method.
func (m *MockConsentGate) RequireCurrent(arg0 context.Context, arg1, arg2 string, arg3 []domain.DataClass) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireCurrent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireCurrent indicates an expected call of RequireCurrent.
func (mr *MockConsentGateMockRecorder) RequireCurrent(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireCurrent", reflect.TypeOf((*MockConsentGate)(nil).RequireCurrent), arg0, arg1, arg2, arg3)
}

// MockRedactor is a mock of Redactor interface.
type MockRedactor struct {
	ctrl     *gomock.Controller
	recorder *MockRedactorMockRecorder
	isgomock struct{}
}

// MockRedactorMockRecorder is the mock recorder for MockRedactor.
type MockRedactorMockRecorder struct {
	mock *MockRedactor
}

// NewMockRedactor creates a new mock instance.
func NewMockRedactor(ctrl *gomock.Controller) *MockRedactor {
	mock := &MockRedactor{ctrl: ctrl}
	mock.recorder = &MockRedactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedactor) EXPECT() *MockRedactorMockRecorder {
	return m.recorder
}

// Redact mocks base method.
func (m *MockRedactor) Redact(arg0 context.Context, arg1 string, arg2 []domain.DataClass) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redact", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Redact indicates an expected call of Redact.
func (mr *MockRedactorMockRecorder) Redact(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redact", reflect.TypeOf((*MockRedactor)(nil).Redact), arg0, arg1, arg2)
}

// MockVendor is a mock of Vendor interface.
type MockVendor struct {
	ctrl     *gomock.Controller
	recorder *MockVendorMockRecorder
	isgomock struct{}
}

// MockVendorMockRecorder is the mock recorder for MockVendor.
type MockVendorMockRecorder struct {
	mock *MockVendor
}

// NewMockVendor creates a new mock instance.
func NewMockVendor(ctrl *gomock.Controller) *MockVendor {
	mock := &MockVendor{ctrl: ctrl}
	mock.recorder = &MockVendorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVendor) EXPECT() *MockVendorMockRecorder {
	return m.recorder
}

// Invoke mocks base method.
func (m *MockVendor) Invoke(arg0 context.Context, arg1 VendorRequest) (VendorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", arg0, arg1)
	ret0, _ := ret[0].(VendorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Invoke indicates an expected call of Invoke.
func (mr *MockVendorMockRecorder) Invoke(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockVendor)(nil).Invoke), arg0, arg1)
}

// MockAuditSink is a mock of AuditSink interface.
type MockAuditSink struct {
	ctrl     *gomock.Controller
	recorder *MockAuditSinkMockRecorder
	isgomock struct{}
}

// MockAuditSinkMockRecorder is the mock recorder for MockAuditSink.
type MockAuditSinkMockRecorder struct {
	mock *MockAuditSink
}

// NewMockAuditSink creates a new mock instance.
func NewMockAuditSink(ctrl *gomock.Controller) *MockAuditSink {
	mock := &MockAuditSink{ctrl: ctrl}
	mock.recorder = &MockAuditSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditSink) EXPECT() *MockAuditSinkMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockAuditSink) Record(arg0 context.Context, arg1 AuditRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockAuditSinkMockRecorder) Record(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockAuditSink)(nil).Record), arg0, arg1)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
