// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/commerce/promotion/application/ports.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/commerce/promotion/application/ports.go -destination services/api/internal/commerce/promotion/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/commerce/promotion/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(ctx context.Context, promotion domain.Promotion, expected uint64, commandID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, promotion, expected, commandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(ctx, promotion, expected, commandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), ctx, promotion, expected, commandID)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Promotion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// FindByCode mocks base method.
func (m *MockRepository) FindByCode(arg0 context.Context, arg1 string) (domain.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", arg0, arg1)
	ret0, _ := ret[0].(domain.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockRepositoryMockRecorder) FindByCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockRepository)(nil).FindByCode), arg0, arg1)
}

// ListByIssuer mocks base method.
func (m *MockRepository) ListByIssuer(ctx context.Context, issuerID string, limit int) ([]domain.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIssuer", ctx, issuerID, limit)
	ret0, _ := ret[0].([]domain.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIssuer indicates an expected call of ListByIssuer.
func (mr *MockRepositoryMockRecorder) ListByIssuer(ctx, issuerID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIssuer", reflect.TypeOf((*MockRepository)(nil).ListByIssuer), ctx, issuerID, limit)
}

// MockIssuers is a mock of Issuers interface.
type MockIssuers struct {
	ctrl     *gomock.Controller
	recorder *MockIssuersMockRecorder
	isgomock struct{}
}

// MockIssuersMockRecorder is the mock recorder for MockIssuers.
type MockIssuersMockRecorder struct {
	mock *MockIssuers
}

// NewMockIssuers creates a new mock instance.
func NewMockIssuers(ctrl *gomock.Controller) *MockIssuers {
	mock := &MockIssuers{ctrl: ctrl}
	mock.recorder = &MockIssuersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssuers) EXPECT() *MockIssuersMockRecorder {
	return m.recorder
}

// Issuing mocks base method.
func (m *MockIssuers) Issuing(ctx context.Context, organizationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issuing", ctx, organizationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issuing indicates an expected call of Issuing.
func (mr *MockIssuersMockRecorder) Issuing(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issuing", reflect.TypeOf((*MockIssuers)(nil).Issuing), ctx, organizationID)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// MemberKey mocks base method.
func (m *MockKeyer) MemberKey(memberID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberKey", memberID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberKey indicates an expected call of MemberKey.
func (mr *MockKeyerMockRecorder) MemberKey(memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberKey", reflect.TypeOf((*MockKeyer)(nil).MemberKey), memberID)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
