// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/matching/coldstart/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthority is a mock of Authority interface.
type MockAuthority struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorityMockRecorder
	isgomock struct{}
}

// MockAuthorityMockRecorder is the mock recorder for MockAuthority.
type MockAuthorityMockRecorder struct {
	mock *MockAuthority
}

// NewMockAuthority creates a new mock instance.
func NewMockAuthority(ctrl *gomock.Controller) *MockAuthority {
	mock := &MockAuthority{ctrl: ctrl}
	mock.recorder = &MockAuthorityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthority) EXPECT() *MockAuthorityMockRecorder {
	return m.recorder
}

// AuthorizeColdStart mocks base method.
func (m *MockAuthority) AuthorizeColdStart(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeColdStart", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthorizeColdStart indicates an expected call of AuthorizeColdStart.
func (mr *MockAuthorityMockRecorder) AuthorizeColdStart(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeColdStart", reflect.TypeOf((*MockAuthority)(nil).AuthorizeColdStart), arg0, arg1)
}

// MockPreferences is a mock of Preferences interface.
type MockPreferences struct {
	ctrl     *gomock.Controller
	recorder *MockPreferencesMockRecorder
	isgomock struct{}
}

// MockPreferencesMockRecorder is the mock recorder for MockPreferences.
type MockPreferencesMockRecorder struct {
	mock *MockPreferences
}

// NewMockPreferences creates a new mock instance.
func NewMockPreferences(ctrl *gomock.Controller) *MockPreferences {
	mock := &MockPreferences{ctrl: ctrl}
	mock.recorder = &MockPreferencesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreferences) EXPECT() *MockPreferencesMockRecorder {
	return m.recorder
}

// Reciprocal mocks base method.
func (m *MockPreferences) Reciprocal(arg0 context.Context, arg1 string, arg2 int) ([]domain.ReciprocalPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reciprocal", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.ReciprocalPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reciprocal indicates an expected call of Reciprocal.
func (mr *MockPreferencesMockRecorder) Reciprocal(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reciprocal", reflect.TypeOf((*MockPreferences)(nil).Reciprocal), arg0, arg1, arg2)
}

// MockTrustPaths is a mock of TrustPaths interface.
type MockTrustPaths struct {
	ctrl     *gomock.Controller
	recorder *MockTrustPathsMockRecorder
	isgomock struct{}
}

// MockTrustPathsMockRecorder is the mock recorder for MockTrustPaths.
type MockTrustPathsMockRecorder struct {
	mock *MockTrustPaths
}

// NewMockTrustPaths creates a new mock instance.
func NewMockTrustPaths(ctrl *gomock.Controller) *MockTrustPaths {
	mock := &MockTrustPaths{ctrl: ctrl}
	mock.recorder = &MockTrustPathsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrustPaths) EXPECT() *MockTrustPathsMockRecorder {
	return m.recorder
}

// Summaries mocks base method.
func (m *MockTrustPaths) Summaries(arg0 context.Context, arg1 string, arg2 int) ([]domain.TrustSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summaries", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.TrustSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summaries indicates an expected call of Summaries.
func (mr *MockTrustPathsMockRecorder) Summaries(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summaries", reflect.TypeOf((*MockTrustPaths)(nil).Summaries), arg0, arg1, arg2)
}

// MockVisibility is a mock of Visibility interface.
type MockVisibility struct {
	ctrl     *gomock.Controller
	recorder *MockVisibilityMockRecorder
	isgomock struct{}
}

// MockVisibilityMockRecorder is the mock recorder for MockVisibility.
type MockVisibilityMockRecorder struct {
	mock *MockVisibility
}

// NewMockVisibility creates a new mock instance.
func NewMockVisibility(ctrl *gomock.Controller) *MockVisibility {
	mock := &MockVisibility{ctrl: ctrl}
	mock.recorder = &MockVisibilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisibility) EXPECT() *MockVisibilityMockRecorder {
	return m.recorder
}

// CanIntroduce mocks base method.
func (m *MockVisibility) CanIntroduce(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanIntroduce", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanIntroduce indicates an expected call of CanIntroduce.
func (mr *MockVisibilityMockRecorder) CanIntroduce(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanIntroduce", reflect.TypeOf((*MockVisibility)(nil).CanIntroduce), arg0, arg1, arg2)
}
