// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/commerce/escrow/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Escrow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// CreateAudited mocks base method.
func (m *MockRepository) CreateAudited(arg0 context.Context, arg1 domain.Escrow, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAudited", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAudited indicates an expected call of CreateAudited.
func (mr *MockRepositoryMockRecorder) CreateAudited(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAudited", reflect.TypeOf((*MockRepository)(nil).CreateAudited), arg0, arg1, arg2)
}

// Find mocks base method.
func (m *MockRepository) Find(arg0 context.Context, arg1 string) (domain.Escrow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Escrow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), arg0, arg1)
}

// FindByCommand mocks base method.
func (m *MockRepository) FindByCommand(arg0 context.Context, arg1 string) (domain.Escrow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommand", arg0, arg1)
	ret0, _ := ret[0].(domain.Escrow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommand indicates an expected call of FindByCommand.
func (mr *MockRepositoryMockRecorder) FindByCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommand", reflect.TypeOf((*MockRepository)(nil).FindByCommand), arg0, arg1)
}

// ListForOwner mocks base method.
func (m *MockRepository) ListForOwner(arg0 context.Context, arg1 string) ([]domain.Escrow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForOwner", arg0, arg1)
	ret0, _ := ret[0].([]domain.Escrow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForOwner indicates an expected call of ListForOwner.
func (mr *MockRepositoryMockRecorder) ListForOwner(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForOwner", reflect.TypeOf((*MockRepository)(nil).ListForOwner), arg0, arg1)
}

// Save mocks base method.
func (m *MockRepository) Save(arg0 context.Context, arg1 domain.Escrow, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), arg0, arg1, arg2, arg3)
}

// SaveAudited mocks base method.
func (m *MockRepository) SaveAudited(arg0 context.Context, arg1 domain.Escrow, arg2 uint64, arg3, arg4, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAudited", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAudited indicates an expected call of SaveAudited.
func (mr *MockRepositoryMockRecorder) SaveAudited(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAudited", reflect.TypeOf((*MockRepository)(nil).SaveAudited), arg0, arg1, arg2, arg3, arg4, arg5)
}

// SettleAudited mocks base method.
func (m *MockRepository) SettleAudited(arg0 context.Context, arg1 domain.Escrow, arg2 uint64, arg3, arg4 string, arg5 domain.Statement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettleAudited", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// SettleAudited indicates an expected call of SettleAudited.
func (mr *MockRepositoryMockRecorder) SettleAudited(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettleAudited", reflect.TypeOf((*MockRepository)(nil).SettleAudited), arg0, arg1, arg2, arg3, arg4, arg5)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
