// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/companions/p2gate/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockConsentSource is a mock of ConsentSource interface.
type MockConsentSource struct {
	ctrl     *gomock.Controller
	recorder *MockConsentSourceMockRecorder
	isgomock struct{}
}

// MockConsentSourceMockRecorder is the mock recorder for MockConsentSource.
type MockConsentSourceMockRecorder struct {
	mock *MockConsentSource
}

// NewMockConsentSource creates a new mock instance.
func NewMockConsentSource(ctrl *gomock.Controller) *MockConsentSource {
	mock := &MockConsentSource{ctrl: ctrl}
	mock.recorder = &MockConsentSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentSource) EXPECT() *MockConsentSourceMockRecorder {
	return m.recorder
}

// CurrentGateConsent mocks base method.
func (m *MockConsentSource) CurrentGateConsent(arg0 context.Context, arg1 string) (domain.GateConsent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentGateConsent", arg0, arg1)
	ret0, _ := ret[0].(domain.GateConsent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentGateConsent indicates an expected call of CurrentGateConsent.
func (mr *MockConsentSourceMockRecorder) CurrentGateConsent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentGateConsent", reflect.TypeOf((*MockConsentSource)(nil).CurrentGateConsent), arg0, arg1)
}

// MockCompanionSource is a mock of CompanionSource interface.
type MockCompanionSource struct {
	ctrl     *gomock.Controller
	recorder *MockCompanionSourceMockRecorder
	isgomock struct{}
}

// MockCompanionSourceMockRecorder is the mock recorder for MockCompanionSource.
type MockCompanionSourceMockRecorder struct {
	mock *MockCompanionSource
}

// NewMockCompanionSource creates a new mock instance.
func NewMockCompanionSource(ctrl *gomock.Controller) *MockCompanionSource {
	mock := &MockCompanionSource{ctrl: ctrl}
	mock.recorder = &MockCompanionSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanionSource) EXPECT() *MockCompanionSourceMockRecorder {
	return m.recorder
}

// CurrentCompanionFacts mocks base method.
func (m *MockCompanionSource) CurrentCompanionFacts(arg0 context.Context, arg1 string) (domain.CompanionFacts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentCompanionFacts", arg0, arg1)
	ret0, _ := ret[0].(domain.CompanionFacts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentCompanionFacts indicates an expected call of CurrentCompanionFacts.
func (mr *MockCompanionSourceMockRecorder) CurrentCompanionFacts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentCompanionFacts", reflect.TypeOf((*MockCompanionSource)(nil).CurrentCompanionFacts), arg0, arg1)
}

// MockSessionAuthenticator is a mock of SessionAuthenticator interface.
type MockSessionAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionAuthenticatorMockRecorder
	isgomock struct{}
}

// MockSessionAuthenticatorMockRecorder is the mock recorder for MockSessionAuthenticator.
type MockSessionAuthenticatorMockRecorder struct {
	mock *MockSessionAuthenticator
}

// NewMockSessionAuthenticator creates a new mock instance.
func NewMockSessionAuthenticator(ctrl *gomock.Controller) *MockSessionAuthenticator {
	mock := &MockSessionAuthenticator{ctrl: ctrl}
	mock.recorder = &MockSessionAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionAuthenticator) EXPECT() *MockSessionAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockSessionAuthenticator) Authenticate(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockSessionAuthenticatorMockRecorder) Authenticate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockSessionAuthenticator)(nil).Authenticate), arg0, arg1, arg2)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Proposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}

// NewTokenRef mocks base method.
func (m *MockIDSource) NewTokenRef() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTokenRef")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewTokenRef indicates an expected call of NewTokenRef.
func (mr *MockIDSourceMockRecorder) NewTokenRef() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTokenRef", reflect.TypeOf((*MockIDSource)(nil).NewTokenRef))
}

// NewWatermarkRef mocks base method.
func (m *MockIDSource) NewWatermarkRef() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWatermarkRef")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewWatermarkRef indicates an expected call of NewWatermarkRef.
func (mr *MockIDSourceMockRecorder) NewWatermarkRef() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWatermarkRef", reflect.TypeOf((*MockIDSource)(nil).NewWatermarkRef))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
