export const landingCopy = {
  en: {
    privacy: "Privacy",
    terms: "Terms",
    motto: "Meet properly.",
    skip: "Skip to content",
    home: "Obiara home",
    how: "How it works",
    why: "Why Obiara",
    language: "Page language",
    login: "Log in",
    signup: "Sign up",
    eyebrow: "ROOTED IN GHANA. OPEN TO CONNECTION.",
    title: "Someone worth",
    accent: "knowing.",
    body: "Meet through people you trust. Start with a voice, share a little of yourself, and give a real connection room to grow.",
    create: "Create your account",
    explore: "Get to know Obiara",
    existing: "Already part of Obiara?",
    age: "For adults 18 and over",
    photoAlt: "Two people sharing a conversation in a leafy Ghanaian courtyard",
    photoLabel: "A little less scrolling.",
    photoTitle: "A little more connection.",
    photoFoot: "Meet properly. Take your time.",
    voiceLabel: "IT STARTS WITH A VOICE",
    voiceTitle: "A hello that feels like you.",
    voiceFoot: "Listen first. Get to know the person.",
    principles: [
      "People before profiles",
      "Voice before appearance",
      "Connection at your pace",
    ],
    howLabel: "A MORE THOUGHTFUL WAY TO MEET",
    howTitle: "Good things start\nwith a proper hello.",
    howBody:
      "You don’t need the perfect opening line. Just bring yourself, and a little intention.",
    steps: [
      {
        title: "Make yourself at home",
        body: "Create your account and take the verification steps. Choose what you share and the boundaries that feel right for you.",
      },
      {
        title: "Let your people connect you",
        body: "Build your circle with people you trust. Introductions come through community, with a little more context and care.",
      },
      {
        title: "Hear a voice. Find a connection.",
        body: "Start by listening. Take turns in conversation and let trust grow before you choose to share more.",
      },
    ],
    whyLabel: "THE OBIARA WAY",
    whyTitle: "You’re a person.\nNot a profile to scroll past.",
    whyBody:
      "Obiara brings the care of a proper introduction online. A place for character, community, and conversations that have somewhere to go.",
    whyItems: [
      "Introductions through trusted circles",
      "Your boundaries, your choices",
      "Space to get to know each other",
    ],
    endLabel: "THERE’S ROOM FOR YOU HERE",
    endTitle: "Your next chapter starts\nwith a hello.",
    endBody: "Come as you are. Meet properly.",
    footer: "Rooted in community. Made for connection.",
    help: "How do I join?",
    languageNote:
      "English and Twi for this page. Account setup continues in English.",
    changed: "Page language changed to English.",
  },
  tw: {
    privacy: "Kokoamsɛm",
    terms: "Nhyehyɛe",
    motto: "Hyia obi yiye.",
    skip: "Kɔ emu nsɛm no so",
    home: "Obiara fie",
    how: "Sɛnea ɛyɛ adwuma",
    why: "Adɛn nti na Obiara",
    language: "Kratafa yi kasa",
    login: "Kɔ wo akawnt mu",
    signup: "Bue akawnt",
    eyebrow: "YƐN NTINI WƆ GHANA. YƐMA NKABOM AKWAABA.",
    title: "Obi a ɛfata sɛ",
    accent: "wuhu no.",
    body: "Fa nnipa a wowɔ wɔn mu ahotoso so hyia obi. Fi ase wɔ nne so, ka wo ho asɛm kakra, na ma abusuabɔ pa nnya bere nnyin.",
    create: "Bue w’akawnt",
    explore: "Hu Obiara yiye",
    existing: "Wowɔ Obiara akawnt dedaw?",
    age: "Ma wɔn a wɔadi mfe 18 ne nea ɛboro saa",
    photoAlt: "Nnipa baanu rebɔ nkɔmmɔ wɔ Ghana adiwo a nhaban atwa ho ahyia",
    photoLabel: "Ma wo telefon nnya ahomegye.",
    photoTitle: "Ma abusuabɔ nnya bere.",
    photoFoot: "Hyia obi yiye. Tɔ wo bo ase.",
    voiceLabel: "ƐFI ASE WƆ NNE SO",
    voiceTitle: "Nkyia a ɛda wo su adi.",
    voiceFoot: "Di kan tie. Hu onipa no yiye.",
    principles: [
      "Onipa ho hia sen ne mfonini",
      "Nne di anim sen ahosɛpɛw",
      "Abusuabɔ wɔ wo bere mu",
    ],
    howLabel: "ƆKWAN PA A WOBƐFA SO AHYIA OBI",
    howTitle: "Adepa fi ase\nwɔ nkyia pa mu.",
    howBody:
      "Ɛnhia sɛ wunya asɛm a ɛyɛ pɛ de fi ase. Bra sɛnea wote, na fa adwene pa bra.",
    steps: [
      {
        title: "Ma ha nyɛ wo fie",
        body: "Bue w’akawnt na di wo ho adanse. Paw nea wopɛ sɛ wokyɛ ne ahye a ɛfata wo.",
      },
      {
        title: "Ma wo nkurɔfo mfa wo nkyerɛ obi",
        body: "Fa nnipa a wowɔ wɔn mu ahotoso yɛ wo kuw. Wɔn na wɔde ɔdɔ ne ahwɛyiye bɛma woahu obi.",
      },
      {
        title: "Tie nne. Nya abusuabɔ.",
        body: "Fi ase denam otie so. Momfa nkɔmmɔ nnidiso nnidiso, na momma ahotoso nnyin ansa na moakyɛ pii.",
      },
    ],
    whyLabel: "OBIARA KWAN",
    whyTitle: "Woyɛ onipa.\nWonyɛ mfonini kɛkɛ.",
    whyBody:
      "Obiara de nkyia pa mu ahwɛyiye ba intanɛt so. Ɛyɛ baabi a suban pa, nkabom ne nkɔmmɔ pa ho hia.",
    whyItems: [
      "Nnipa a wowɔ wɔn mu ahotoso na wɔde wo kyerɛ obi",
      "Wo ahye, wo paw",
      "Bere a mode behu mo ho yiye",
    ],
    endLabel: "WUNYA BAABI WƆ HA",
    endTitle: "Wo mfiase foforo\nfi nkyia so.",
    endBody: "Bra sɛnea wote. Hyia obi yiye.",
    footer: "Yɛn ntini wɔ nkabom mu. Yɛde yɛ abusuabɔ.",
    help: "Mɛyɛ dɛn akɔ mu?",
    languageNote:
      "Kratafa yi wɔ Borɔfo ne Twi mu. Akawnt nhyehyɛe no toa so wɔ Borɔfo mu.",
    changed: "Kratafa yi kasa asesa ayɛ Twi.",
  },
} as const;
export type LandingLanguage = keyof typeof landingCopy;
