// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/trust/application/ports.go
//
// Generated by this command:
//
//	mockgen -source=services/api/internal/trust/application/ports.go -destination=services/api/internal/trust/application/mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/trust/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockRepository) Find(arg0 context.Context, arg1 string) (domain.Edge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Edge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), arg0, arg1)
}

// Outgoing mocks base method.
func (m *MockRepository) Outgoing(arg0 context.Context, arg1 []string) ([]domain.Edge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Outgoing", arg0, arg1)
	ret0, _ := ret[0].([]domain.Edge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Outgoing indicates an expected call of Outgoing.
func (mr *MockRepositoryMockRecorder) Outgoing(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Outgoing", reflect.TypeOf((*MockRepository)(nil).Outgoing), arg0, arg1)
}

// Save mocks base method.
func (m *MockRepository) Save(arg0 context.Context, arg1 domain.Edge, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), arg0, arg1, arg2, arg3)
}

// MockProjectionAuthorizer is a mock of ProjectionAuthorizer interface.
type MockProjectionAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockProjectionAuthorizerMockRecorder
	isgomock struct{}
}

// MockProjectionAuthorizerMockRecorder is the mock recorder for MockProjectionAuthorizer.
type MockProjectionAuthorizerMockRecorder struct {
	mock *MockProjectionAuthorizer
}

// NewMockProjectionAuthorizer creates a new mock instance.
func NewMockProjectionAuthorizer(ctrl *gomock.Controller) *MockProjectionAuthorizer {
	mock := &MockProjectionAuthorizer{ctrl: ctrl}
	mock.recorder = &MockProjectionAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectionAuthorizer) EXPECT() *MockProjectionAuthorizerMockRecorder {
	return m.recorder
}

// CanProject mocks base method.
func (m *MockProjectionAuthorizer) CanProject(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanProject", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanProject indicates an expected call of CanProject.
func (mr *MockProjectionAuthorizerMockRecorder) CanProject(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanProject", reflect.TypeOf((*MockProjectionAuthorizer)(nil).CanProject), arg0, arg1, arg2)
}

// MockConsentEvaluator is a mock of ConsentEvaluator interface.
type MockConsentEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockConsentEvaluatorMockRecorder
	isgomock struct{}
}

// MockConsentEvaluatorMockRecorder is the mock recorder for MockConsentEvaluator.
type MockConsentEvaluatorMockRecorder struct {
	mock *MockConsentEvaluator
}

// NewMockConsentEvaluator creates a new mock instance.
func NewMockConsentEvaluator(ctrl *gomock.Controller) *MockConsentEvaluator {
	mock := &MockConsentEvaluator{ctrl: ctrl}
	mock.recorder = &MockConsentEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentEvaluator) EXPECT() *MockConsentEvaluatorMockRecorder {
	return m.recorder
}

// Allows mocks base method.
func (m *MockConsentEvaluator) Allows(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allows", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allows indicates an expected call of Allows.
func (mr *MockConsentEvaluatorMockRecorder) Allows(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allows", reflect.TypeOf((*MockConsentEvaluator)(nil).Allows), arg0, arg1, arg2)
}
