// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/suban/application/suban.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/suban/application/suban.go -destination services/api/internal/suban/application/mock_suban_test.go -package application EventStore
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/suban/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventStore is a mock of EventStore interface.
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *MockEventStoreMockRecorder
	isgomock struct{}
}

// MockEventStoreMockRecorder is the mock recorder for MockEventStore.
type MockEventStoreMockRecorder struct {
	mock *MockEventStore
}

// NewMockEventStore creates a new mock instance.
func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &MockEventStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStore) EXPECT() *MockEventStoreMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockEventStore) Append(arg0 context.Context, arg1 domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockEventStoreMockRecorder) Append(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockEventStore)(nil).Append), arg0, arg1)
}

// CountForSubjectSince mocks base method.
func (m *MockEventStore) CountForSubjectSince(arg0 context.Context, arg1 string, arg2 domain.Kind, arg3 time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountForSubjectSince", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountForSubjectSince indicates an expected call of CountForSubjectSince.
func (mr *MockEventStoreMockRecorder) CountForSubjectSince(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountForSubjectSince", reflect.TypeOf((*MockEventStore)(nil).CountForSubjectSince), arg0, arg1, arg2, arg3)
}

// ListForSubject mocks base method.
func (m *MockEventStore) ListForSubject(arg0 context.Context, arg1 string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForSubject", arg0, arg1)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForSubject indicates an expected call of ListForSubject.
func (mr *MockEventStoreMockRecorder) ListForSubject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForSubject", reflect.TypeOf((*MockEventStore)(nil).ListForSubject), arg0, arg1)
}
