// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/admin/application/admin.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/admin/application/admin.go -destination services/api/internal/admin/application/mock_admin_test.go -package application PrincipalRepository,ChallengeRepository,SessionRepository,AccessAudit,OperatorMailer
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/admin/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPrincipalRepository is a mock of PrincipalRepository interface.
type MockPrincipalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrincipalRepositoryMockRecorder
	isgomock struct{}
}

// MockPrincipalRepositoryMockRecorder is the mock recorder for MockPrincipalRepository.
type MockPrincipalRepositoryMockRecorder struct {
	mock *MockPrincipalRepository
}

// NewMockPrincipalRepository creates a new mock instance.
func NewMockPrincipalRepository(ctrl *gomock.Controller) *MockPrincipalRepository {
	mock := &MockPrincipalRepository{ctrl: ctrl}
	mock.recorder = &MockPrincipalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrincipalRepository) EXPECT() *MockPrincipalRepositoryMockRecorder {
	return m.recorder
}

// ApproveRoleChange mocks base method.
func (m *MockPrincipalRepository) ApproveRoleChange(arg0 context.Context, arg1 domain.RoleChange, arg2 domain.Principal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveRoleChange", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveRoleChange indicates an expected call of ApproveRoleChange.
func (mr *MockPrincipalRepositoryMockRecorder) ApproveRoleChange(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveRoleChange", reflect.TypeOf((*MockPrincipalRepository)(nil).ApproveRoleChange), arg0, arg1, arg2)
}

// CreateRoleChange mocks base method.
func (m *MockPrincipalRepository) CreateRoleChange(ctx context.Context, change domain.RoleChange, guardLastAdmin bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoleChange", ctx, change, guardLastAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoleChange indicates an expected call of CreateRoleChange.
func (mr *MockPrincipalRepositoryMockRecorder) CreateRoleChange(ctx, change, guardLastAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoleChange", reflect.TypeOf((*MockPrincipalRepository)(nil).CreateRoleChange), ctx, change, guardLastAdmin)
}

// CreateWithAudit mocks base method.
func (m *MockPrincipalRepository) CreateWithAudit(ctx context.Context, principal domain.Principal, actorID, action string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithAudit", ctx, principal, actorID, action, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithAudit indicates an expected call of CreateWithAudit.
func (mr *MockPrincipalRepositoryMockRecorder) CreateWithAudit(ctx, principal, actorID, action, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithAudit", reflect.TypeOf((*MockPrincipalRepository)(nil).CreateWithAudit), ctx, principal, actorID, action, at)
}

// FindByEmail mocks base method.
func (m *MockPrincipalRepository) FindByEmail(arg0 context.Context, arg1 string) (domain.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", arg0, arg1)
	ret0, _ := ret[0].(domain.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockPrincipalRepositoryMockRecorder) FindByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockPrincipalRepository)(nil).FindByEmail), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockPrincipalRepository) FindByID(arg0 context.Context, arg1 string) (domain.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPrincipalRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPrincipalRepository)(nil).FindByID), arg0, arg1)
}

// FindRoleChange mocks base method.
func (m *MockPrincipalRepository) FindRoleChange(arg0 context.Context, arg1 string) (domain.RoleChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoleChange", arg0, arg1)
	ret0, _ := ret[0].(domain.RoleChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoleChange indicates an expected call of FindRoleChange.
func (mr *MockPrincipalRepositoryMockRecorder) FindRoleChange(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoleChange", reflect.TypeOf((*MockPrincipalRepository)(nil).FindRoleChange), arg0, arg1)
}

// List mocks base method.
func (m *MockPrincipalRepository) List(arg0 context.Context) ([]domain.Principal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]domain.Principal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPrincipalRepositoryMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPrincipalRepository)(nil).List), arg0)
}

// ListPendingRoleChanges mocks base method.
func (m *MockPrincipalRepository) ListPendingRoleChanges(arg0 context.Context) ([]domain.RoleChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingRoleChanges", arg0)
	ret0, _ := ret[0].([]domain.RoleChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingRoleChanges indicates an expected call of ListPendingRoleChanges.
func (mr *MockPrincipalRepositoryMockRecorder) ListPendingRoleChanges(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingRoleChanges", reflect.TypeOf((*MockPrincipalRepository)(nil).ListPendingRoleChanges), arg0)
}

// UpdateWithAudit mocks base method.
func (m *MockPrincipalRepository) UpdateWithAudit(ctx context.Context, principal domain.Principal, guardLastAdmin bool, actorID, action string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithAudit", ctx, principal, guardLastAdmin, actorID, action, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithAudit indicates an expected call of UpdateWithAudit.
func (mr *MockPrincipalRepositoryMockRecorder) UpdateWithAudit(ctx, principal, guardLastAdmin, actorID, action, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithAudit", reflect.TypeOf((*MockPrincipalRepository)(nil).UpdateWithAudit), ctx, principal, guardLastAdmin, actorID, action, at)
}

// MockChallengeRepository is a mock of ChallengeRepository interface.
type MockChallengeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeRepositoryMockRecorder
	isgomock struct{}
}

// MockChallengeRepositoryMockRecorder is the mock recorder for MockChallengeRepository.
type MockChallengeRepositoryMockRecorder struct {
	mock *MockChallengeRepository
}

// NewMockChallengeRepository creates a new mock instance.
func NewMockChallengeRepository(ctrl *gomock.Controller) *MockChallengeRepository {
	mock := &MockChallengeRepository{ctrl: ctrl}
	mock.recorder = &MockChallengeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeRepository) EXPECT() *MockChallengeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChallengeRepository) Create(arg0 context.Context, arg1 domain.Challenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockChallengeRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChallengeRepository)(nil).Create), arg0, arg1)
}

// LatestForPrincipal mocks base method.
func (m *MockChallengeRepository) LatestForPrincipal(arg0 context.Context, arg1 string) (domain.Challenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestForPrincipal", arg0, arg1)
	ret0, _ := ret[0].(domain.Challenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestForPrincipal indicates an expected call of LatestForPrincipal.
func (mr *MockChallengeRepositoryMockRecorder) LatestForPrincipal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestForPrincipal", reflect.TypeOf((*MockChallengeRepository)(nil).LatestForPrincipal), arg0, arg1)
}

// Update mocks base method.
func (m *MockChallengeRepository) Update(arg0 context.Context, arg1 domain.Challenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockChallengeRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChallengeRepository)(nil).Update), arg0, arg1)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(arg0 context.Context, arg1 domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockSessionRepository) FindByID(arg0 context.Context, arg1 string) (domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSessionRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSessionRepository)(nil).FindByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockSessionRepository) Update(arg0 context.Context, arg1 domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepository)(nil).Update), arg0, arg1)
}

// MockAccessAudit is a mock of AccessAudit interface.
type MockAccessAudit struct {
	ctrl     *gomock.Controller
	recorder *MockAccessAuditMockRecorder
	isgomock struct{}
}

// MockAccessAuditMockRecorder is the mock recorder for MockAccessAudit.
type MockAccessAuditMockRecorder struct {
	mock *MockAccessAudit
}

// NewMockAccessAudit creates a new mock instance.
func NewMockAccessAudit(ctrl *gomock.Controller) *MockAccessAudit {
	mock := &MockAccessAudit{ctrl: ctrl}
	mock.recorder = &MockAccessAuditMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessAudit) EXPECT() *MockAccessAuditMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockAccessAudit) Append(ctx context.Context, actorID, action, target string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, actorID, action, target, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockAccessAuditMockRecorder) Append(ctx, actorID, action, target, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockAccessAudit)(nil).Append), ctx, actorID, action, target, at)
}

// MockOperatorMailer is a mock of OperatorMailer interface.
type MockOperatorMailer struct {
	ctrl     *gomock.Controller
	recorder *MockOperatorMailerMockRecorder
	isgomock struct{}
}

// MockOperatorMailerMockRecorder is the mock recorder for MockOperatorMailer.
type MockOperatorMailerMockRecorder struct {
	mock *MockOperatorMailer
}

// NewMockOperatorMailer creates a new mock instance.
func NewMockOperatorMailer(ctrl *gomock.Controller) *MockOperatorMailer {
	mock := &MockOperatorMailer{ctrl: ctrl}
	mock.recorder = &MockOperatorMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperatorMailer) EXPECT() *MockOperatorMailerMockRecorder {
	return m.recorder
}

// SendInvite mocks base method.
func (m *MockOperatorMailer) SendInvite(ctx context.Context, email string, roles []domain.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendInvite", ctx, email, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendInvite indicates an expected call of SendInvite.
func (mr *MockOperatorMailerMockRecorder) SendInvite(ctx, email, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInvite", reflect.TypeOf((*MockOperatorMailer)(nil).SendInvite), ctx, email, roles)
}

// SendMfaCode mocks base method.
func (m *MockOperatorMailer) SendMfaCode(ctx context.Context, email, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMfaCode", ctx, email, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMfaCode indicates an expected call of SendMfaCode.
func (mr *MockOperatorMailerMockRecorder) SendMfaCode(ctx, email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMfaCode", reflect.TypeOf((*MockOperatorMailer)(nil).SendMfaCode), ctx, email, code)
}
