// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLocaleSource is a mock of LocaleSource interface.
type MockLocaleSource struct {
	ctrl     *gomock.Controller
	recorder *MockLocaleSourceMockRecorder
	isgomock struct{}
}

// MockLocaleSourceMockRecorder is the mock recorder for MockLocaleSource.
type MockLocaleSourceMockRecorder struct {
	mock *MockLocaleSource
}

// NewMockLocaleSource creates a new mock instance.
func NewMockLocaleSource(ctrl *gomock.Controller) *MockLocaleSource {
	mock := &MockLocaleSource{ctrl: ctrl}
	mock.recorder = &MockLocaleSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocaleSource) EXPECT() *MockLocaleSourceMockRecorder {
	return m.recorder
}

// CurrentLocale mocks base method.
func (m *MockLocaleSource) CurrentLocale(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentLocale", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentLocale indicates an expected call of CurrentLocale.
func (mr *MockLocaleSourceMockRecorder) CurrentLocale(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentLocale", reflect.TypeOf((*MockLocaleSource)(nil).CurrentLocale), arg0)
}

// MockLocaleCatalog is a mock of LocaleCatalog interface.
type MockLocaleCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockLocaleCatalogMockRecorder
	isgomock struct{}
}

// MockLocaleCatalogMockRecorder is the mock recorder for MockLocaleCatalog.
type MockLocaleCatalogMockRecorder struct {
	mock *MockLocaleCatalog
}

// NewMockLocaleCatalog creates a new mock instance.
func NewMockLocaleCatalog(ctrl *gomock.Controller) *MockLocaleCatalog {
	mock := &MockLocaleCatalog{ctrl: ctrl}
	mock.recorder = &MockLocaleCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocaleCatalog) EXPECT() *MockLocaleCatalogMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockLocaleCatalog) Resolve(arg0 context.Context, arg1 string) (LocaleReview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", arg0, arg1)
	ret0, _ := ret[0].(LocaleReview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockLocaleCatalogMockRecorder) Resolve(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockLocaleCatalog)(nil).Resolve), arg0, arg1)
}

// MockMediaInspector is a mock of MediaInspector interface.
type MockMediaInspector struct {
	ctrl     *gomock.Controller
	recorder *MockMediaInspectorMockRecorder
	isgomock struct{}
}

// MockMediaInspectorMockRecorder is the mock recorder for MockMediaInspector.
type MockMediaInspectorMockRecorder struct {
	mock *MockMediaInspector
}

// NewMockMediaInspector creates a new mock instance.
func NewMockMediaInspector(ctrl *gomock.Controller) *MockMediaInspector {
	mock := &MockMediaInspector{ctrl: ctrl}
	mock.recorder = &MockMediaInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaInspector) EXPECT() *MockMediaInspectorMockRecorder {
	return m.recorder
}

// Inspect mocks base method.
func (m *MockMediaInspector) Inspect(arg0 context.Context, arg1 string) (MediaMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", arg0, arg1)
	ret0, _ := ret[0].(MediaMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockMediaInspectorMockRecorder) Inspect(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockMediaInspector)(nil).Inspect), arg0, arg1)
}

// MockAdvisor is a mock of Advisor interface.
type MockAdvisor struct {
	ctrl     *gomock.Controller
	recorder *MockAdvisorMockRecorder
	isgomock struct{}
}

// MockAdvisorMockRecorder is the mock recorder for MockAdvisor.
type MockAdvisorMockRecorder struct {
	mock *MockAdvisor
}

// NewMockAdvisor creates a new mock instance.
func NewMockAdvisor(ctrl *gomock.Controller) *MockAdvisor {
	mock := &MockAdvisor{ctrl: ctrl}
	mock.recorder = &MockAdvisorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvisor) EXPECT() *MockAdvisorMockRecorder {
	return m.recorder
}

// Screen mocks base method.
func (m *MockAdvisor) Screen(arg0 context.Context, arg1 ScreeningInput) (Advisory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Screen", arg0, arg1)
	ret0, _ := ret[0].(Advisory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Screen indicates an expected call of Screen.
func (mr *MockAdvisorMockRecorder) Screen(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Screen", reflect.TypeOf((*MockAdvisor)(nil).Screen), arg0, arg1)
}

// MockAdjudicator is a mock of Adjudicator interface.
type MockAdjudicator struct {
	ctrl     *gomock.Controller
	recorder *MockAdjudicatorMockRecorder
	isgomock struct{}
}

// MockAdjudicatorMockRecorder is the mock recorder for MockAdjudicator.
type MockAdjudicatorMockRecorder struct {
	mock *MockAdjudicator
}

// NewMockAdjudicator creates a new mock instance.
func NewMockAdjudicator(ctrl *gomock.Controller) *MockAdjudicator {
	mock := &MockAdjudicator{ctrl: ctrl}
	mock.recorder = &MockAdjudicatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdjudicator) EXPECT() *MockAdjudicatorMockRecorder {
	return m.recorder
}

// Decide mocks base method.
func (m *MockAdjudicator) Decide(arg0 context.Context, arg1 ScreeningInput, arg2 Advisory) (Adjudication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decide", arg0, arg1, arg2)
	ret0, _ := ret[0].(Adjudication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decide indicates an expected call of Decide.
func (mr *MockAdjudicatorMockRecorder) Decide(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decide", reflect.TypeOf((*MockAdjudicator)(nil).Decide), arg0, arg1, arg2)
}

// MockHumanReview is a mock of HumanReview interface.
type MockHumanReview struct {
	ctrl     *gomock.Controller
	recorder *MockHumanReviewMockRecorder
	isgomock struct{}
}

// MockHumanReviewMockRecorder is the mock recorder for MockHumanReview.
type MockHumanReviewMockRecorder struct {
	mock *MockHumanReview
}

// NewMockHumanReview creates a new mock instance.
func NewMockHumanReview(ctrl *gomock.Controller) *MockHumanReview {
	mock := &MockHumanReview{ctrl: ctrl}
	mock.recorder = &MockHumanReviewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHumanReview) EXPECT() *MockHumanReviewMockRecorder {
	return m.recorder
}

// Route mocks base method.
func (m *MockHumanReview) Route(arg0 context.Context, arg1 ReviewCase) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Route", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Route indicates an expected call of Route.
func (mr *MockHumanReviewMockRecorder) Route(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Route", reflect.TypeOf((*MockHumanReview)(nil).Route), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
