// Code generated by MockGen. DO NOT EDIT.
// Source: internal/safety/application/cases.go
//
// Generated by this command:
//
//	mockgen -source internal/safety/application/cases.go -destination internal/safety/application/mock_cases_test.go -package application CaseRepository
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/internal/safety/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCaseRepository is a mock of CaseRepository interface.
type MockCaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCaseRepositoryMockRecorder
	isgomock struct{}
}

// MockCaseRepositoryMockRecorder is the mock recorder for MockCaseRepository.
type MockCaseRepositoryMockRecorder struct {
	mock *MockCaseRepository
}

// NewMockCaseRepository creates a new mock instance.
func NewMockCaseRepository(ctrl *gomock.Controller) *MockCaseRepository {
	mock := &MockCaseRepository{ctrl: ctrl}
	mock.recorder = &MockCaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseRepository) EXPECT() *MockCaseRepositoryMockRecorder {
	return m.recorder
}

// CountBreached mocks base method.
func (m *MockCaseRepository) CountBreached(arg0 context.Context, arg1 time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBreached", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBreached indicates an expected call of CountBreached.
func (mr *MockCaseRepositoryMockRecorder) CountBreached(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBreached", reflect.TypeOf((*MockCaseRepository)(nil).CountBreached), arg0, arg1)
}

// Create mocks base method.
func (m *MockCaseRepository) Create(arg0 context.Context, arg1 domain.Case) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCaseRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCaseRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockCaseRepository) FindByID(arg0 context.Context, arg1 string) (domain.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCaseRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCaseRepository)(nil).FindByID), arg0, arg1)
}

// NextQueued mocks base method.
func (m *MockCaseRepository) NextQueued(arg0 context.Context, arg1 domain.Queue, arg2 int) ([]domain.Case, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextQueued", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Case)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextQueued indicates an expected call of NextQueued.
func (mr *MockCaseRepositoryMockRecorder) NextQueued(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextQueued", reflect.TypeOf((*MockCaseRepository)(nil).NextQueued), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockCaseRepository) Update(arg0 context.Context, arg1 domain.Case) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCaseRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCaseRepository)(nil).Update), arg0, arg1)
}
