// Code generated by MockGen. DO NOT EDIT.
// Source: internal/safety/application/actions.go
//
// Generated by this command:
//
//	mockgen -source internal/safety/application/actions.go -destination internal/safety/application/mock_actions_test.go -package application ActionLog,IdentityEnforcement,SessionRevoker,DeviceBlocklister
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/internal/safety/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockActionLog is a mock of ActionLog interface.
type MockActionLog struct {
	ctrl     *gomock.Controller
	recorder *MockActionLogMockRecorder
	isgomock struct{}
}

// MockActionLogMockRecorder is the mock recorder for MockActionLog.
type MockActionLogMockRecorder struct {
	mock *MockActionLog
}

// NewMockActionLog creates a new mock instance.
func NewMockActionLog(ctrl *gomock.Controller) *MockActionLog {
	mock := &MockActionLog{ctrl: ctrl}
	mock.recorder = &MockActionLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionLog) EXPECT() *MockActionLogMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockActionLog) Append(arg0 context.Context, arg1 domain.ActionRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockActionLogMockRecorder) Append(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockActionLog)(nil).Append), arg0, arg1)
}

// CountForSubject mocks base method.
func (m *MockActionLog) CountForSubject(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountForSubject", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountForSubject indicates an expected call of CountForSubject.
func (mr *MockActionLogMockRecorder) CountForSubject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountForSubject", reflect.TypeOf((*MockActionLog)(nil).CountForSubject), arg0, arg1)
}

// MockIdentityEnforcement is a mock of IdentityEnforcement interface.
type MockIdentityEnforcement struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityEnforcementMockRecorder
	isgomock struct{}
}

// MockIdentityEnforcementMockRecorder is the mock recorder for MockIdentityEnforcement.
type MockIdentityEnforcementMockRecorder struct {
	mock *MockIdentityEnforcement
}

// NewMockIdentityEnforcement creates a new mock instance.
func NewMockIdentityEnforcement(ctrl *gomock.Controller) *MockIdentityEnforcement {
	mock := &MockIdentityEnforcement{ctrl: ctrl}
	mock.recorder = &MockIdentityEnforcementMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityEnforcement) EXPECT() *MockIdentityEnforcementMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockIdentityEnforcement) Block(ctx context.Context, accountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", ctx, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Block indicates an expected call of Block.
func (mr *MockIdentityEnforcementMockRecorder) Block(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockIdentityEnforcement)(nil).Block), ctx, accountID)
}

// Suspend mocks base method.
func (m *MockIdentityEnforcement) Suspend(ctx context.Context, accountID string, until time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", ctx, accountID, until)
	ret0, _ := ret[0].(error)
	return ret0
}

// Suspend indicates an expected call of Suspend.
func (mr *MockIdentityEnforcementMockRecorder) Suspend(ctx, accountID, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockIdentityEnforcement)(nil).Suspend), ctx, accountID, until)
}

// MockSessionRevoker is a mock of SessionRevoker interface.
type MockSessionRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRevokerMockRecorder
	isgomock struct{}
}

// MockSessionRevokerMockRecorder is the mock recorder for MockSessionRevoker.
type MockSessionRevokerMockRecorder struct {
	mock *MockSessionRevoker
}

// NewMockSessionRevoker creates a new mock instance.
func NewMockSessionRevoker(ctrl *gomock.Controller) *MockSessionRevoker {
	mock := &MockSessionRevoker{ctrl: ctrl}
	mock.recorder = &MockSessionRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRevoker) EXPECT() *MockSessionRevokerMockRecorder {
	return m.recorder
}

// RevokeMemberSessions mocks base method.
func (m *MockSessionRevoker) RevokeMemberSessions(ctx context.Context, memberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeMemberSessions", ctx, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeMemberSessions indicates an expected call of RevokeMemberSessions.
func (mr *MockSessionRevokerMockRecorder) RevokeMemberSessions(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeMemberSessions", reflect.TypeOf((*MockSessionRevoker)(nil).RevokeMemberSessions), ctx, memberID)
}

// MockDeviceBlocklister is a mock of DeviceBlocklister interface.
type MockDeviceBlocklister struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceBlocklisterMockRecorder
	isgomock struct{}
}

// MockDeviceBlocklisterMockRecorder is the mock recorder for MockDeviceBlocklister.
type MockDeviceBlocklisterMockRecorder struct {
	mock *MockDeviceBlocklister
}

// NewMockDeviceBlocklister creates a new mock instance.
func NewMockDeviceBlocklister(ctrl *gomock.Controller) *MockDeviceBlocklister {
	mock := &MockDeviceBlocklister{ctrl: ctrl}
	mock.recorder = &MockDeviceBlocklisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceBlocklister) EXPECT() *MockDeviceBlocklisterMockRecorder {
	return m.recorder
}

// Blocklist mocks base method.
func (m *MockDeviceBlocklister) Blocklist(ctx context.Context, subjectID, reason string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocklist", ctx, subjectID, reason, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Blocklist indicates an expected call of Blocklist.
func (mr *MockDeviceBlocklisterMockRecorder) Blocklist(ctx, subjectID, reason, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocklist", reflect.TypeOf((*MockDeviceBlocklister)(nil).Blocklist), ctx, subjectID, reason, at)
}
