// Code generated by MockGen. DO NOT EDIT.
// Source: internal/safety/application/care.go
//
// Generated by this command:
//
//	mockgen -source internal/safety/application/care.go -destination internal/safety/application/mock_care_test.go -package application CareRepository,QuieteningStore
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/internal/safety/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCareRepository is a mock of CareRepository interface.
type MockCareRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCareRepositoryMockRecorder
	isgomock struct{}
}

// MockCareRepositoryMockRecorder is the mock recorder for MockCareRepository.
type MockCareRepositoryMockRecorder struct {
	mock *MockCareRepository
}

// NewMockCareRepository creates a new mock instance.
func NewMockCareRepository(ctrl *gomock.Controller) *MockCareRepository {
	mock := &MockCareRepository{ctrl: ctrl}
	mock.recorder = &MockCareRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCareRepository) EXPECT() *MockCareRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCareRepository) Create(arg0 context.Context, arg1 domain.CareCase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCareRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCareRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockCareRepository) FindByID(arg0 context.Context, arg1 string) (domain.CareCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.CareCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCareRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCareRepository)(nil).FindByID), arg0, arg1)
}

// NextOpen mocks base method.
func (m *MockCareRepository) NextOpen(arg0 context.Context, arg1 int) ([]domain.CareCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextOpen", arg0, arg1)
	ret0, _ := ret[0].([]domain.CareCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextOpen indicates an expected call of NextOpen.
func (mr *MockCareRepositoryMockRecorder) NextOpen(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextOpen", reflect.TypeOf((*MockCareRepository)(nil).NextOpen), arg0, arg1)
}

// Update mocks base method.
func (m *MockCareRepository) Update(arg0 context.Context, arg1 domain.CareCase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCareRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCareRepository)(nil).Update), arg0, arg1)
}

// MockQuieteningStore is a mock of QuieteningStore interface.
type MockQuieteningStore struct {
	ctrl     *gomock.Controller
	recorder *MockQuieteningStoreMockRecorder
	isgomock struct{}
}

// MockQuieteningStoreMockRecorder is the mock recorder for MockQuieteningStore.
type MockQuieteningStoreMockRecorder struct {
	mock *MockQuieteningStore
}

// NewMockQuieteningStore creates a new mock instance.
func NewMockQuieteningStore(ctrl *gomock.Controller) *MockQuieteningStore {
	mock := &MockQuieteningStore{ctrl: ctrl}
	mock.recorder = &MockQuieteningStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuieteningStore) EXPECT() *MockQuieteningStoreMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockQuieteningStore) Set(ctx context.Context, subjectID string, until time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, subjectID, until)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockQuieteningStoreMockRecorder) Set(ctx, subjectID, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockQuieteningStore)(nil).Set), ctx, subjectID, until)
}
