// Code generated by MockGen. DO NOT EDIT.
// Source: application/nomination.go
//
// Generated by this command:
//
//	mockgen -source application/nomination.go -destination application/mock_nomination_test.go -package application NominationRepository,NotificationSender
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/internal/notifications/whatsapp/domain"
	domain0 "github.com/stanleyHayes/obiara/services/api/internal/companions/nnoboa/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNominationRepository is a mock of NominationRepository interface.
type MockNominationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNominationRepositoryMockRecorder
	isgomock struct{}
}

// MockNominationRepositoryMockRecorder is the mock recorder for MockNominationRepository.
type MockNominationRepositoryMockRecorder struct {
	mock *MockNominationRepository
}

// NewMockNominationRepository creates a new mock instance.
func NewMockNominationRepository(ctrl *gomock.Controller) *MockNominationRepository {
	mock := &MockNominationRepository{ctrl: ctrl}
	mock.recorder = &MockNominationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNominationRepository) EXPECT() *MockNominationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNominationRepository) Create(ctx context.Context, n domain0.Nomination) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNominationRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNominationRepository)(nil).Create), ctx, n)
}

// FindByID mocks base method.
func (m *MockNominationRepository) FindByID(ctx context.Context, id string) (domain0.Nomination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain0.Nomination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockNominationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNominationRepository)(nil).FindByID), ctx, id)
}

// HasPendingForKin mocks base method.
func (m *MockNominationRepository) HasPendingForKin(ctx context.Context, memberID, kinPhone string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPendingForKin", ctx, memberID, kinPhone)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPendingForKin indicates an expected call of HasPendingForKin.
func (mr *MockNominationRepositoryMockRecorder) HasPendingForKin(ctx, memberID, kinPhone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPendingForKin", reflect.TypeOf((*MockNominationRepository)(nil).HasPendingForKin), ctx, memberID, kinPhone)
}

// ListByMember mocks base method.
func (m *MockNominationRepository) ListByMember(ctx context.Context, memberID string) ([]domain0.Nomination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMember", ctx, memberID)
	ret0, _ := ret[0].([]domain0.Nomination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMember indicates an expected call of ListByMember.
func (mr *MockNominationRepositoryMockRecorder) ListByMember(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMember", reflect.TypeOf((*MockNominationRepository)(nil).ListByMember), ctx, memberID)
}

// Update mocks base method.
func (m *MockNominationRepository) Update(ctx context.Context, n domain0.Nomination) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNominationRepositoryMockRecorder) Update(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNominationRepository)(nil).Update), ctx, n)
}

// MockNotificationSender is a mock of NotificationSender interface.
type MockNotificationSender struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSenderMockRecorder
	isgomock struct{}
}

// MockNotificationSenderMockRecorder is the mock recorder for MockNotificationSender.
type MockNotificationSenderMockRecorder struct {
	mock *MockNotificationSender
}

// NewMockNotificationSender creates a new mock instance.
func NewMockNotificationSender(ctrl *gomock.Controller) *MockNotificationSender {
	mock := &MockNotificationSender{ctrl: ctrl}
	mock.recorder = &MockNotificationSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSender) EXPECT() *MockNotificationSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockNotificationSender) Send(ctx context.Context, msg domain.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationSenderMockRecorder) Send(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationSender)(nil).Send), ctx, msg)
}
