// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/fire/application/fire.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/fire/application/fire.go -destination services/api/internal/fire/application/mock_fire_test.go -package application FireRepository
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/fire/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFireRepository is a mock of FireRepository interface.
type MockFireRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFireRepositoryMockRecorder
	isgomock struct{}
}

// MockFireRepositoryMockRecorder is the mock recorder for MockFireRepository.
type MockFireRepositoryMockRecorder struct {
	mock *MockFireRepository
}

// NewMockFireRepository creates a new mock instance.
func NewMockFireRepository(ctrl *gomock.Controller) *MockFireRepository {
	mock := &MockFireRepository{ctrl: ctrl}
	mock.recorder = &MockFireRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFireRepository) EXPECT() *MockFireRepositoryMockRecorder {
	return m.recorder
}

// AdmitTx mocks base method.
func (m *MockFireRepository) AdmitTx(ctx context.Context, fireID, memberID string, now time.Time) (domain.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdmitTx", ctx, fireID, memberID, now)
	ret0, _ := ret[0].(domain.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdmitTx indicates an expected call of AdmitTx.
func (mr *MockFireRepositoryMockRecorder) AdmitTx(ctx, fireID, memberID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdmitTx", reflect.TypeOf((*MockFireRepository)(nil).AdmitTx), ctx, fireID, memberID, now)
}

// CancelTx mocks base method.
func (m *MockFireRepository) CancelTx(ctx context.Context, fireID, memberID string, now time.Time) (*domain.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTx", ctx, fireID, memberID, now)
	ret0, _ := ret[0].(*domain.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelTx indicates an expected call of CancelTx.
func (mr *MockFireRepositoryMockRecorder) CancelTx(ctx, fireID, memberID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTx", reflect.TypeOf((*MockFireRepository)(nil).CancelTx), ctx, fireID, memberID, now)
}

// Create mocks base method.
func (m *MockFireRepository) Create(arg0 context.Context, arg1 domain.Fire) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFireRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFireRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockFireRepository) FindByID(arg0 context.Context, arg1 string) (domain.Fire, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Fire)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFireRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFireRepository)(nil).FindByID), arg0, arg1)
}

// FindRSVP mocks base method.
func (m *MockFireRepository) FindRSVP(arg0 context.Context, arg1, arg2 string) (domain.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRSVP", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRSVP indicates an expected call of FindRSVP.
func (mr *MockFireRepositoryMockRecorder) FindRSVP(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRSVP", reflect.TypeOf((*MockFireRepository)(nil).FindRSVP), arg0, arg1, arg2)
}

// ListGoing mocks base method.
func (m *MockFireRepository) ListGoing(arg0 context.Context, arg1 string) ([]domain.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGoing", arg0, arg1)
	ret0, _ := ret[0].([]domain.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGoing indicates an expected call of ListGoing.
func (mr *MockFireRepositoryMockRecorder) ListGoing(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGoing", reflect.TypeOf((*MockFireRepository)(nil).ListGoing), arg0, arg1)
}

// ListUpcoming mocks base method.
func (m *MockFireRepository) ListUpcoming(arg0 context.Context, arg1 time.Time, arg2 int) ([]domain.Fire, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUpcoming", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Fire)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUpcoming indicates an expected call of ListUpcoming.
func (mr *MockFireRepositoryMockRecorder) ListUpcoming(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUpcoming", reflect.TypeOf((*MockFireRepository)(nil).ListUpcoming), arg0, arg1, arg2)
}

// UpdateStatus mocks base method.
func (m *MockFireRepository) UpdateStatus(arg0 context.Context, arg1 domain.Fire) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFireRepositoryMockRecorder) UpdateStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFireRepository)(nil).UpdateStatus), arg0, arg1)
}
