// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/seed/sprout/application/ports.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/seed/sprout/application/ports.go -destination services/api/internal/seed/sprout/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/seed/sprout/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDeclineLock is a mock of DeclineLock interface.
type MockDeclineLock struct {
	ctrl     *gomock.Controller
	recorder *MockDeclineLockMockRecorder
	isgomock struct{}
}

// MockDeclineLockMockRecorder is the mock recorder for MockDeclineLock.
type MockDeclineLockMockRecorder struct {
	mock *MockDeclineLock
}

// NewMockDeclineLock creates a new mock instance.
func NewMockDeclineLock(ctrl *gomock.Controller) *MockDeclineLock {
	mock := &MockDeclineLock{ctrl: ctrl}
	mock.recorder = &MockDeclineLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeclineLock) EXPECT() *MockDeclineLockMockRecorder {
	return m.recorder
}

// Locked mocks base method.
func (m *MockDeclineLock) Locked(ctx context.Context, sowerID, targetID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locked", ctx, sowerID, targetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Locked indicates an expected call of Locked.
func (mr *MockDeclineLockMockRecorder) Locked(ctx, sowerID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locked", reflect.TypeOf((*MockDeclineLock)(nil).Locked), ctx, sowerID, targetID)
}

// MockAllowance is a mock of Allowance interface.
type MockAllowance struct {
	ctrl     *gomock.Controller
	recorder *MockAllowanceMockRecorder
	isgomock struct{}
}

// MockAllowanceMockRecorder is the mock recorder for MockAllowance.
type MockAllowanceMockRecorder struct {
	mock *MockAllowance
}

// NewMockAllowance creates a new mock instance.
func NewMockAllowance(ctrl *gomock.Controller) *MockAllowance {
	mock := &MockAllowance{ctrl: ctrl}
	mock.recorder = &MockAllowanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllowance) EXPECT() *MockAllowanceMockRecorder {
	return m.recorder
}

// Spend mocks base method.
func (m *MockAllowance) Spend(ctx context.Context, memberID, commandID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spend", ctx, memberID, commandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Spend indicates an expected call of Spend.
func (mr *MockAllowanceMockRecorder) Spend(ctx, memberID, commandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spend", reflect.TypeOf((*MockAllowance)(nil).Spend), ctx, memberID, commandID)
}

// MockListenGate is a mock of ListenGate interface.
type MockListenGate struct {
	ctrl     *gomock.Controller
	recorder *MockListenGateMockRecorder
	isgomock struct{}
}

// MockListenGateMockRecorder is the mock recorder for MockListenGate.
type MockListenGateMockRecorder struct {
	mock *MockListenGate
}

// NewMockListenGate creates a new mock instance.
func NewMockListenGate(ctrl *gomock.Controller) *MockListenGate {
	mock := &MockListenGate{ctrl: ctrl}
	mock.recorder = &MockListenGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenGate) EXPECT() *MockListenGateMockRecorder {
	return m.recorder
}

// Heard mocks base method.
func (m *MockListenGate) Heard(ctx context.Context, listenerID, targetID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heard", ctx, listenerID, targetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Heard indicates an expected call of Heard.
func (mr *MockListenGateMockRecorder) Heard(ctx, listenerID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heard", reflect.TypeOf((*MockListenGate)(nil).Heard), ctx, listenerID, targetID)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AppendExchange mocks base method.
func (m *MockRepository) AppendExchange(arg0 context.Context, arg1 domain.Doorway, arg2 uint64) (domain.Doorway, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendExchange", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Doorway)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AppendExchange indicates an expected call of AppendExchange.
func (mr *MockRepositoryMockRecorder) AppendExchange(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendExchange", reflect.TypeOf((*MockRepository)(nil).AppendExchange), arg0, arg1, arg2)
}

// FindDoorway mocks base method.
func (m *MockRepository) FindDoorway(arg0 context.Context, arg1 string) (domain.Doorway, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDoorway", arg0, arg1)
	ret0, _ := ret[0].(domain.Doorway)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDoorway indicates an expected call of FindDoorway.
func (mr *MockRepositoryMockRecorder) FindDoorway(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDoorway", reflect.TypeOf((*MockRepository)(nil).FindDoorway), arg0, arg1)
}

// RecordIntent mocks base method.
func (m *MockRepository) RecordIntent(arg0 context.Context, arg1 domain.Intent) (*domain.Doorway, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordIntent", arg0, arg1)
	ret0, _ := ret[0].(*domain.Doorway)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecordIntent indicates an expected call of RecordIntent.
func (mr *MockRepositoryMockRecorder) RecordIntent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordIntent", reflect.TypeOf((*MockRepository)(nil).RecordIntent), arg0, arg1)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(namespace, value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", namespace, value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(namespace, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), namespace, value)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
