// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/analytics/p0gate/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDefinitionCatalog is a mock of DefinitionCatalog interface.
type MockDefinitionCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockDefinitionCatalogMockRecorder
	isgomock struct{}
}

// MockDefinitionCatalogMockRecorder is the mock recorder for MockDefinitionCatalog.
type MockDefinitionCatalogMockRecorder struct {
	mock *MockDefinitionCatalog
}

// NewMockDefinitionCatalog creates a new mock instance.
func NewMockDefinitionCatalog(ctrl *gomock.Controller) *MockDefinitionCatalog {
	mock := &MockDefinitionCatalog{ctrl: ctrl}
	mock.recorder = &MockDefinitionCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefinitionCatalog) EXPECT() *MockDefinitionCatalogMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockDefinitionCatalog) Current(arg0 context.Context) (domain.Definition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", arg0)
	ret0, _ := ret[0].(domain.Definition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockDefinitionCatalogMockRecorder) Current(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockDefinitionCatalog)(nil).Current), arg0)
}

// MockAggregateSource is a mock of AggregateSource interface.
type MockAggregateSource struct {
	ctrl     *gomock.Controller
	recorder *MockAggregateSourceMockRecorder
	isgomock struct{}
}

// MockAggregateSourceMockRecorder is the mock recorder for MockAggregateSource.
type MockAggregateSourceMockRecorder struct {
	mock *MockAggregateSource
}

// NewMockAggregateSource creates a new mock instance.
func NewMockAggregateSource(ctrl *gomock.Controller) *MockAggregateSource {
	mock := &MockAggregateSource{ctrl: ctrl}
	mock.recorder = &MockAggregateSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAggregateSource) EXPECT() *MockAggregateSourceMockRecorder {
	return m.recorder
}

// Current mocks base method.
func (m *MockAggregateSource) Current(arg0 context.Context, arg1 string) (domain.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", arg0, arg1)
	ret0, _ := ret[0].(domain.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockAggregateSourceMockRecorder) Current(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockAggregateSource)(nil).Current), arg0, arg1)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockRepository) Insert(arg0 context.Context, arg1 domain.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockRepositoryMockRecorder) Insert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRepository)(nil).Insert), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
