// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/fire/incident/application/ports.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/fire/incident/application/ports.go -destination services/api/internal/fire/incident/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/fire/incident/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(arg0 context.Context, arg1 domain.Incident, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), arg0, arg1, arg2, arg3)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// FindByCase mocks base method.
func (m *MockRepository) FindByCase(arg0 context.Context, arg1 string) (domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCase", arg0, arg1)
	ret0, _ := ret[0].(domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCase indicates an expected call of FindByCase.
func (mr *MockRepositoryMockRecorder) FindByCase(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCase", reflect.TypeOf((*MockRepository)(nil).FindByCase), arg0, arg1)
}

// FindByCommand mocks base method.
func (m *MockRepository) FindByCommand(arg0 context.Context, arg1 string) (domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommand", arg0, arg1)
	ret0, _ := ret[0].(domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommand indicates an expected call of FindByCommand.
func (mr *MockRepositoryMockRecorder) FindByCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommand", reflect.TypeOf((*MockRepository)(nil).FindByCommand), arg0, arg1)
}

// MockParticipantAuthority is a mock of ParticipantAuthority interface.
type MockParticipantAuthority struct {
	ctrl     *gomock.Controller
	recorder *MockParticipantAuthorityMockRecorder
	isgomock struct{}
}

// MockParticipantAuthorityMockRecorder is the mock recorder for MockParticipantAuthority.
type MockParticipantAuthorityMockRecorder struct {
	mock *MockParticipantAuthority
}

// NewMockParticipantAuthority creates a new mock instance.
func NewMockParticipantAuthority(ctrl *gomock.Controller) *MockParticipantAuthority {
	mock := &MockParticipantAuthority{ctrl: ctrl}
	mock.recorder = &MockParticipantAuthorityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticipantAuthority) EXPECT() *MockParticipantAuthorityMockRecorder {
	return m.recorder
}

// RequireParticipant mocks base method.
func (m *MockParticipantAuthority) RequireParticipant(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireParticipant", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireParticipant indicates an expected call of RequireParticipant.
func (mr *MockParticipantAuthorityMockRecorder) RequireParticipant(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireParticipant", reflect.TypeOf((*MockParticipantAuthority)(nil).RequireParticipant), arg0, arg1, arg2)
}

// MockSafetyAction is a mock of SafetyAction interface.
type MockSafetyAction struct {
	ctrl     *gomock.Controller
	recorder *MockSafetyActionMockRecorder
	isgomock struct{}
}

// MockSafetyActionMockRecorder is the mock recorder for MockSafetyAction.
type MockSafetyActionMockRecorder struct {
	mock *MockSafetyAction
}

// NewMockSafetyAction creates a new mock instance.
func NewMockSafetyAction(ctrl *gomock.Controller) *MockSafetyAction {
	mock := &MockSafetyAction{ctrl: ctrl}
	mock.recorder = &MockSafetyActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSafetyAction) EXPECT() *MockSafetyActionMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockSafetyAction) Apply(arg0 context.Context, arg1, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockSafetyActionMockRecorder) Apply(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockSafetyAction)(nil).Apply), arg0, arg1, arg2, arg3, arg4)
}

// MockTrustSafetyRouter is a mock of TrustSafetyRouter interface.
type MockTrustSafetyRouter struct {
	ctrl     *gomock.Controller
	recorder *MockTrustSafetyRouterMockRecorder
	isgomock struct{}
}

// MockTrustSafetyRouterMockRecorder is the mock recorder for MockTrustSafetyRouter.
type MockTrustSafetyRouterMockRecorder struct {
	mock *MockTrustSafetyRouter
}

// NewMockTrustSafetyRouter creates a new mock instance.
func NewMockTrustSafetyRouter(ctrl *gomock.Controller) *MockTrustSafetyRouter {
	mock := &MockTrustSafetyRouter{ctrl: ctrl}
	mock.recorder = &MockTrustSafetyRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrustSafetyRouter) EXPECT() *MockTrustSafetyRouterMockRecorder {
	return m.recorder
}

// Revalidate mocks base method.
func (m *MockTrustSafetyRouter) Revalidate(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revalidate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revalidate indicates an expected call of Revalidate.
func (mr *MockTrustSafetyRouterMockRecorder) Revalidate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revalidate", reflect.TypeOf((*MockTrustSafetyRouter)(nil).Revalidate), arg0)
}

// Route mocks base method.
func (m *MockTrustSafetyRouter) Route(arg0 context.Context, arg1 domain.Case) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Route", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Route indicates an expected call of Route.
func (mr *MockTrustSafetyRouterMockRecorder) Route(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Route", reflect.TypeOf((*MockTrustSafetyRouter)(nil).Route), arg0, arg1)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
