// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/safeguarding/application/ports.go
//
// Generated by this command:
//
//	mockgen -source=services/api/internal/safeguarding/application/ports.go -destination=services/api/internal/safeguarding/application/mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/safeguarding/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRestrictionStore is a mock of RestrictionStore interface.
type MockRestrictionStore struct {
	ctrl     *gomock.Controller
	recorder *MockRestrictionStoreMockRecorder
	isgomock struct{}
}

// MockRestrictionStoreMockRecorder is the mock recorder for MockRestrictionStore.
type MockRestrictionStoreMockRecorder struct {
	mock *MockRestrictionStore
}

// NewMockRestrictionStore creates a new mock instance.
func NewMockRestrictionStore(ctrl *gomock.Controller) *MockRestrictionStore {
	mock := &MockRestrictionStore{ctrl: ctrl}
	mock.recorder = &MockRestrictionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestrictionStore) EXPECT() *MockRestrictionStoreMockRecorder {
	return m.recorder
}

// CompletePurge mocks base method.
func (m *MockRestrictionStore) CompletePurge(arg0 context.Context, arg1 domain.Restriction, arg2 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompletePurge", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompletePurge indicates an expected call of CompletePurge.
func (mr *MockRestrictionStoreMockRecorder) CompletePurge(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompletePurge", reflect.TypeOf((*MockRestrictionStore)(nil).CompletePurge), arg0, arg1, arg2)
}

// CreateBlocked mocks base method.
func (m *MockRestrictionStore) CreateBlocked(arg0 context.Context, arg1 domain.Restriction, arg2 PurgeJob) (domain.Restriction, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlocked", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Restriction)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateBlocked indicates an expected call of CreateBlocked.
func (mr *MockRestrictionStoreMockRecorder) CreateBlocked(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlocked", reflect.TypeOf((*MockRestrictionStore)(nil).CreateBlocked), arg0, arg1, arg2)
}

// FindByID mocks base method.
func (m *MockRestrictionStore) FindByID(arg0 context.Context, arg1 string) (domain.Restriction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Restriction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRestrictionStoreMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRestrictionStore)(nil).FindByID), arg0, arg1)
}

// FindBySubjectKey mocks base method.
func (m *MockRestrictionStore) FindBySubjectKey(arg0 context.Context, arg1 string) (domain.Restriction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubjectKey", arg0, arg1)
	ret0, _ := ret[0].(domain.Restriction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubjectKey indicates an expected call of FindBySubjectKey.
func (mr *MockRestrictionStoreMockRecorder) FindBySubjectKey(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubjectKey", reflect.TypeOf((*MockRestrictionStore)(nil).FindBySubjectKey), arg0, arg1)
}

// FindPending mocks base method.
func (m *MockRestrictionStore) FindPending(arg0 context.Context, arg1 time.Time, arg2 int) ([]PurgeJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPending", arg0, arg1, arg2)
	ret0, _ := ret[0].([]PurgeJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPending indicates an expected call of FindPending.
func (mr *MockRestrictionStoreMockRecorder) FindPending(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPending", reflect.TypeOf((*MockRestrictionStore)(nil).FindPending), arg0, arg1, arg2)
}

// MockArtifactPurger is a mock of ArtifactPurger interface.
type MockArtifactPurger struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactPurgerMockRecorder
	isgomock struct{}
}

// MockArtifactPurgerMockRecorder is the mock recorder for MockArtifactPurger.
type MockArtifactPurgerMockRecorder struct {
	mock *MockArtifactPurger
}

// NewMockArtifactPurger creates a new mock instance.
func NewMockArtifactPurger(ctrl *gomock.Controller) *MockArtifactPurger {
	mock := &MockArtifactPurger{ctrl: ctrl}
	mock.recorder = &MockArtifactPurgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactPurger) EXPECT() *MockArtifactPurgerMockRecorder {
	return m.recorder
}

// Purge mocks base method.
func (m *MockArtifactPurger) Purge(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purge", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purge indicates an expected call of Purge.
func (mr *MockArtifactPurgerMockRecorder) Purge(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockArtifactPurger)(nil).Purge), arg0, arg1, arg2)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), arg0)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
