// Code generated by MockGen. DO NOT EDIT.
// Source: harness.go
//
// Generated by this command:
//
//	mockgen -source=harness.go -destination=mock_transport_test.go -package=fireacceptance
//

// Package fireacceptance is a generated GoMock package.
package fireacceptance

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProbeTransport is a mock of ProbeTransport interface.
type MockProbeTransport struct {
	ctrl     *gomock.Controller
	recorder *MockProbeTransportMockRecorder
	isgomock struct{}
}

// MockProbeTransportMockRecorder is the mock recorder for MockProbeTransport.
type MockProbeTransportMockRecorder struct {
	mock *MockProbeTransport
}

// NewMockProbeTransport creates a new mock instance.
func NewMockProbeTransport(ctrl *gomock.Controller) *MockProbeTransport {
	mock := &MockProbeTransport{ctrl: ctrl}
	mock.recorder = &MockProbeTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbeTransport) EXPECT() *MockProbeTransportMockRecorder {
	return m.recorder
}

// Probe mocks base method.
func (m *MockProbeTransport) Probe(arg0 context.Context, arg1 Probe) (Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", arg0, arg1)
	ret0, _ := ret[0].(Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Probe indicates an expected call of Probe.
func (mr *MockProbeTransportMockRecorder) Probe(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockProbeTransport)(nil).Probe), arg0, arg1)
}
