// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/marketpack/application/marketpack.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/marketpack/application/marketpack.go -destination services/api/internal/marketpack/application/mock_marketpack_test.go -package application PackRepository,ConfigAudit
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/marketpack/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPackRepository is a mock of PackRepository interface.
type MockPackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPackRepositoryMockRecorder
	isgomock struct{}
}

// MockPackRepositoryMockRecorder is the mock recorder for MockPackRepository.
type MockPackRepositoryMockRecorder struct {
	mock *MockPackRepository
}

// NewMockPackRepository creates a new mock instance.
func NewMockPackRepository(ctrl *gomock.Controller) *MockPackRepository {
	mock := &MockPackRepository{ctrl: ctrl}
	mock.recorder = &MockPackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackRepository) EXPECT() *MockPackRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPackRepository) Create(arg0 context.Context, arg1 domain.MarketPack) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPackRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPackRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockPackRepository) FindByID(arg0 context.Context, arg1 string) (domain.MarketPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.MarketPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPackRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPackRepository)(nil).FindByID), arg0, arg1)
}

// ListPublished mocks base method.
func (m *MockPackRepository) ListPublished(arg0 context.Context) ([]domain.MarketPack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublished", arg0)
	ret0, _ := ret[0].([]domain.MarketPack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublished indicates an expected call of ListPublished.
func (mr *MockPackRepositoryMockRecorder) ListPublished(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublished", reflect.TypeOf((*MockPackRepository)(nil).ListPublished), arg0)
}

// Update mocks base method.
func (m *MockPackRepository) Update(arg0 context.Context, arg1 domain.MarketPack) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPackRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPackRepository)(nil).Update), arg0, arg1)
}

// MockConfigAudit is a mock of ConfigAudit interface.
type MockConfigAudit struct {
	ctrl     *gomock.Controller
	recorder *MockConfigAuditMockRecorder
	isgomock struct{}
}

// MockConfigAuditMockRecorder is the mock recorder for MockConfigAudit.
type MockConfigAuditMockRecorder struct {
	mock *MockConfigAudit
}

// NewMockConfigAudit creates a new mock instance.
func NewMockConfigAudit(ctrl *gomock.Controller) *MockConfigAudit {
	mock := &MockConfigAudit{ctrl: ctrl}
	mock.recorder = &MockConfigAuditMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigAudit) EXPECT() *MockConfigAuditMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockConfigAudit) Append(ctx context.Context, actorID, action, packID string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, actorID, action, packID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockConfigAuditMockRecorder) Append(ctx, actorID, action, packID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockConfigAudit)(nil).Append), ctx, actorID, action, packID, at)
}
