// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/verification/application/service.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/verification/application/service.go -destination services/api/internal/verification/application/mock_service_test.go -package application CaseRepository,VerificationProvider,TierTransitions
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/verification/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationProvider is a mock of VerificationProvider interface.
type MockVerificationProvider struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationProviderMockRecorder
	isgomock struct{}
}

// MockVerificationProviderMockRecorder is the mock recorder for MockVerificationProvider.
type MockVerificationProviderMockRecorder struct {
	mock *MockVerificationProvider
}

// NewMockVerificationProvider creates a new mock instance.
func NewMockVerificationProvider(ctrl *gomock.Controller) *MockVerificationProvider {
	mock := &MockVerificationProvider{ctrl: ctrl}
	mock.recorder = &MockVerificationProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationProvider) EXPECT() *MockVerificationProviderMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockVerificationProvider) Verify(arg0 context.Context, arg1 ProviderRequest) (ProviderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", arg0, arg1)
	ret0, _ := ret[0].(ProviderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockVerificationProviderMockRecorder) Verify(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockVerificationProvider)(nil).Verify), arg0, arg1)
}

// MockCaseRepository is a mock of CaseRepository interface.
type MockCaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCaseRepositoryMockRecorder
	isgomock struct{}
}

// MockCaseRepositoryMockRecorder is the mock recorder for MockCaseRepository.
type MockCaseRepositoryMockRecorder struct {
	mock *MockCaseRepository
}

// NewMockCaseRepository creates a new mock instance.
func NewMockCaseRepository(ctrl *gomock.Controller) *MockCaseRepository {
	mock := &MockCaseRepository{ctrl: ctrl}
	mock.recorder = &MockCaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaseRepository) EXPECT() *MockCaseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCaseRepository) Create(arg0 context.Context, arg1 domain.VerificationCase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCaseRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCaseRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockCaseRepository) FindByID(arg0 context.Context, arg1 string) (domain.VerificationCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.VerificationCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCaseRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCaseRepository)(nil).FindByID), arg0, arg1)
}

// NextQueued mocks base method.
func (m *MockCaseRepository) NextQueued(arg0 context.Context, arg1 int) ([]domain.VerificationCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextQueued", arg0, arg1)
	ret0, _ := ret[0].([]domain.VerificationCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextQueued indicates an expected call of NextQueued.
func (mr *MockCaseRepositoryMockRecorder) NextQueued(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextQueued", reflect.TypeOf((*MockCaseRepository)(nil).NextQueued), arg0, arg1)
}

// Update mocks base method.
func (m *MockCaseRepository) Update(arg0 context.Context, arg1 domain.VerificationCase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCaseRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCaseRepository)(nil).Update), arg0, arg1)
}

// MockTierTransitions is a mock of TierTransitions interface.
type MockTierTransitions struct {
	ctrl     *gomock.Controller
	recorder *MockTierTransitionsMockRecorder
	isgomock struct{}
}

// MockTierTransitionsMockRecorder is the mock recorder for MockTierTransitions.
type MockTierTransitionsMockRecorder struct {
	mock *MockTierTransitions
}

// NewMockTierTransitions creates a new mock instance.
func NewMockTierTransitions(ctrl *gomock.Controller) *MockTierTransitions {
	mock := &MockTierTransitions{ctrl: ctrl}
	mock.recorder = &MockTierTransitionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTierTransitions) EXPECT() *MockTierTransitionsMockRecorder {
	return m.recorder
}

// Transition mocks base method.
func (m *MockTierTransitions) Transition(ctx context.Context, accountID string, target int, reason, actorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transition", ctx, accountID, target, reason, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transition indicates an expected call of Transition.
func (mr *MockTierTransitionsMockRecorder) Transition(ctx, accountID, target, reason, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transition", reflect.TypeOf((*MockTierTransitions)(nil).Transition), ctx, accountID, target, reason, actorID)
}
