// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/games/competition/application/ports.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/games/competition/application/ports.go -destination services/api/internal/games/competition/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/games/competition/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(arg0 context.Context, arg1 domain.Competition, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), arg0, arg1, arg2, arg3)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Competition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockRepository) Find(arg0 context.Context, arg1 string) (domain.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), arg0, arg1)
}

// FindByCommand mocks base method.
func (m *MockRepository) FindByCommand(arg0 context.Context, arg1 string) (domain.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCommand", arg0, arg1)
	ret0, _ := ret[0].(domain.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCommand indicates an expected call of FindByCommand.
func (mr *MockRepositoryMockRecorder) FindByCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCommand", reflect.TypeOf((*MockRepository)(nil).FindByCommand), arg0, arg1)
}

// MockAuthority is a mock of Authority interface.
type MockAuthority struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorityMockRecorder
	isgomock struct{}
}

// MockAuthorityMockRecorder is the mock recorder for MockAuthority.
type MockAuthorityMockRecorder struct {
	mock *MockAuthority
}

// NewMockAuthority creates a new mock instance.
func NewMockAuthority(ctrl *gomock.Controller) *MockAuthority {
	mock := &MockAuthority{ctrl: ctrl}
	mock.recorder = &MockAuthorityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthority) EXPECT() *MockAuthorityMockRecorder {
	return m.recorder
}

// RequireCohortMember mocks base method.
func (m *MockAuthority) RequireCohortMember(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireCohortMember", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireCohortMember indicates an expected call of RequireCohortMember.
func (mr *MockAuthorityMockRecorder) RequireCohortMember(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireCohortMember", reflect.TypeOf((*MockAuthority)(nil).RequireCohortMember), arg0, arg1, arg2)
}

// RequireReviewer mocks base method.
func (m *MockAuthority) RequireReviewer(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireReviewer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequireReviewer indicates an expected call of RequireReviewer.
func (mr *MockAuthorityMockRecorder) RequireReviewer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireReviewer", reflect.TypeOf((*MockAuthority)(nil).RequireReviewer), arg0, arg1)
}

// RevalidateCohort mocks base method.
func (m *MockAuthority) RevalidateCohort(arg0 context.Context, arg1 string, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevalidateCohort", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevalidateCohort indicates an expected call of RevalidateCohort.
func (mr *MockAuthorityMockRecorder) RevalidateCohort(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevalidateCohort", reflect.TypeOf((*MockAuthority)(nil).RevalidateCohort), arg0, arg1, arg2)
}

// MockOptIn is a mock of OptIn interface.
type MockOptIn struct {
	ctrl     *gomock.Controller
	recorder *MockOptInMockRecorder
	isgomock struct{}
}

// MockOptInMockRecorder is the mock recorder for MockOptIn.
type MockOptInMockRecorder struct {
	mock *MockOptIn
}

// NewMockOptIn creates a new mock instance.
func NewMockOptIn(ctrl *gomock.Controller) *MockOptIn {
	mock := &MockOptIn{ctrl: ctrl}
	mock.recorder = &MockOptInMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOptIn) EXPECT() *MockOptInMockRecorder {
	return m.recorder
}

// Revalidate mocks base method.
func (m *MockOptIn) Revalidate(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revalidate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revalidate indicates an expected call of Revalidate.
func (mr *MockOptInMockRecorder) Revalidate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revalidate", reflect.TypeOf((*MockOptIn)(nil).Revalidate), arg0, arg1, arg2)
}

// MockResultVerifier is a mock of ResultVerifier interface.
type MockResultVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockResultVerifierMockRecorder
	isgomock struct{}
}

// MockResultVerifierMockRecorder is the mock recorder for MockResultVerifier.
type MockResultVerifierMockRecorder struct {
	mock *MockResultVerifier
}

// NewMockResultVerifier creates a new mock instance.
func NewMockResultVerifier(ctrl *gomock.Controller) *MockResultVerifier {
	mock := &MockResultVerifier{ctrl: ctrl}
	mock.recorder = &MockResultVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultVerifier) EXPECT() *MockResultVerifierMockRecorder {
	return m.recorder
}

// Revalidate mocks base method.
func (m *MockResultVerifier) Revalidate(arg0 context.Context, arg1, arg2, arg3, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revalidate", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revalidate indicates an expected call of Revalidate.
func (mr *MockResultVerifierMockRecorder) Revalidate(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revalidate", reflect.TypeOf((*MockResultVerifier)(nil).Revalidate), arg0, arg1, arg2, arg3, arg4)
}

// MockFairPlayVerifier is a mock of FairPlayVerifier interface.
type MockFairPlayVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockFairPlayVerifierMockRecorder
	isgomock struct{}
}

// MockFairPlayVerifierMockRecorder is the mock recorder for MockFairPlayVerifier.
type MockFairPlayVerifierMockRecorder struct {
	mock *MockFairPlayVerifier
}

// NewMockFairPlayVerifier creates a new mock instance.
func NewMockFairPlayVerifier(ctrl *gomock.Controller) *MockFairPlayVerifier {
	mock := &MockFairPlayVerifier{ctrl: ctrl}
	mock.recorder = &MockFairPlayVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFairPlayVerifier) EXPECT() *MockFairPlayVerifierMockRecorder {
	return m.recorder
}

// Revalidate mocks base method.
func (m *MockFairPlayVerifier) Revalidate(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revalidate", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revalidate indicates an expected call of Revalidate.
func (mr *MockFairPlayVerifierMockRecorder) Revalidate(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revalidate", reflect.TypeOf((*MockFairPlayVerifier)(nil).Revalidate), arg0, arg1, arg2, arg3)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), arg0, arg1)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
