// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/ritual/application/dispatch.go
//
// Generated by this command:
//
//	mockgen -source internal/notifications/ritual/application/dispatch.go -destination internal/notifications/ritual/application/mock_dispatch_test.go -package application MemberSource,PreferenceReader,Decider,FireSource
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/internal/notifications/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMemberSource is a mock of MemberSource interface.
type MockMemberSource struct {
	ctrl     *gomock.Controller
	recorder *MockMemberSourceMockRecorder
	isgomock struct{}
}

// MockMemberSourceMockRecorder is the mock recorder for MockMemberSource.
type MockMemberSourceMockRecorder struct {
	mock *MockMemberSource
}

// NewMockMemberSource creates a new mock instance.
func NewMockMemberSource(ctrl *gomock.Controller) *MockMemberSource {
	mock := &MockMemberSource{ctrl: ctrl}
	mock.recorder = &MockMemberSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberSource) EXPECT() *MockMemberSourceMockRecorder {
	return m.recorder
}

// ListActiveIDs mocks base method.
func (m *MockMemberSource) ListActiveIDs(arg0 context.Context, arg1 int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveIDs", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveIDs indicates an expected call of ListActiveIDs.
func (mr *MockMemberSourceMockRecorder) ListActiveIDs(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveIDs", reflect.TypeOf((*MockMemberSource)(nil).ListActiveIDs), arg0, arg1)
}

// MockPreferenceReader is a mock of PreferenceReader interface.
type MockPreferenceReader struct {
	ctrl     *gomock.Controller
	recorder *MockPreferenceReaderMockRecorder
	isgomock struct{}
}

// MockPreferenceReaderMockRecorder is the mock recorder for MockPreferenceReader.
type MockPreferenceReaderMockRecorder struct {
	mock *MockPreferenceReader
}

// NewMockPreferenceReader creates a new mock instance.
func NewMockPreferenceReader(ctrl *gomock.Controller) *MockPreferenceReader {
	mock := &MockPreferenceReader{ctrl: ctrl}
	mock.recorder = &MockPreferenceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreferenceReader) EXPECT() *MockPreferenceReaderMockRecorder {
	return m.recorder
}

// TimezoneFor mocks base method.
func (m *MockPreferenceReader) TimezoneFor(ctx context.Context, memberID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimezoneFor", ctx, memberID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TimezoneFor indicates an expected call of TimezoneFor.
func (mr *MockPreferenceReaderMockRecorder) TimezoneFor(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimezoneFor", reflect.TypeOf((*MockPreferenceReader)(nil).TimezoneFor), ctx, memberID)
}

// MockDecider is a mock of Decider interface.
type MockDecider struct {
	ctrl     *gomock.Controller
	recorder *MockDeciderMockRecorder
	isgomock struct{}
}

// MockDeciderMockRecorder is the mock recorder for MockDecider.
type MockDeciderMockRecorder struct {
	mock *MockDecider
}

// NewMockDecider creates a new mock instance.
func NewMockDecider(ctrl *gomock.Controller) *MockDecider {
	mock := &MockDecider{ctrl: ctrl}
	mock.recorder = &MockDeciderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecider) EXPECT() *MockDeciderMockRecorder {
	return m.recorder
}

// Decide mocks base method.
func (m *MockDecider) Decide(ctx context.Context, memberID string, category domain.Category) (domain.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decide", ctx, memberID, category)
	ret0, _ := ret[0].(domain.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decide indicates an expected call of Decide.
func (mr *MockDeciderMockRecorder) Decide(ctx, memberID, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decide", reflect.TypeOf((*MockDecider)(nil).Decide), ctx, memberID, category)
}

// MockFireSource is a mock of FireSource interface.
type MockFireSource struct {
	ctrl     *gomock.Controller
	recorder *MockFireSourceMockRecorder
	isgomock struct{}
}

// MockFireSourceMockRecorder is the mock recorder for MockFireSource.
type MockFireSourceMockRecorder struct {
	mock *MockFireSource
}

// NewMockFireSource creates a new mock instance.
func NewMockFireSource(ctrl *gomock.Controller) *MockFireSource {
	mock := &MockFireSource{ctrl: ctrl}
	mock.recorder = &MockFireSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFireSource) EXPECT() *MockFireSourceMockRecorder {
	return m.recorder
}

// StartingWithin mocks base method.
func (m *MockFireSource) StartingWithin(ctx context.Context, from, until time.Time) ([]FireWindow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartingWithin", ctx, from, until)
	ret0, _ := ret[0].([]FireWindow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartingWithin indicates an expected call of StartingWithin.
func (mr *MockFireSourceMockRecorder) StartingWithin(ctx, from, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartingWithin", reflect.TypeOf((*MockFireSource)(nil).StartingWithin), ctx, from, until)
}
