// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/seed/sow/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScreening is a mock of Screening interface.
type MockScreening struct {
	ctrl     *gomock.Controller
	recorder *MockScreeningMockRecorder
	isgomock struct{}
}

// MockScreeningMockRecorder is the mock recorder for MockScreening.
type MockScreeningMockRecorder struct {
	mock *MockScreening
}

// NewMockScreening creates a new mock instance.
func NewMockScreening(ctrl *gomock.Controller) *MockScreening {
	mock := &MockScreening{ctrl: ctrl}
	mock.recorder = &MockScreeningMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreening) EXPECT() *MockScreeningMockRecorder {
	return m.recorder
}

// Screen mocks base method.
func (m *MockScreening) Screen(arg0 context.Context, arg1 string, arg2 []string) (ScreeningDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Screen", arg0, arg1, arg2)
	ret0, _ := ret[0].(ScreeningDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Screen indicates an expected call of Screen.
func (mr *MockScreeningMockRecorder) Screen(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Screen", reflect.TypeOf((*MockScreening)(nil).Screen), arg0, arg1, arg2)
}

// MockAcceptance is a mock of Acceptance interface.
type MockAcceptance struct {
	ctrl     *gomock.Controller
	recorder *MockAcceptanceMockRecorder
	isgomock struct{}
}

// MockAcceptanceMockRecorder is the mock recorder for MockAcceptance.
type MockAcceptanceMockRecorder struct {
	mock *MockAcceptance
}

// NewMockAcceptance creates a new mock instance.
func NewMockAcceptance(ctrl *gomock.Controller) *MockAcceptance {
	mock := &MockAcceptance{ctrl: ctrl}
	mock.recorder = &MockAcceptanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcceptance) EXPECT() *MockAcceptanceMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockAcceptance) Accept(arg0 context.Context, arg1 domain.Sow) (domain.Sow, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", arg0, arg1)
	ret0, _ := ret[0].(domain.Sow)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Accept indicates an expected call of Accept.
func (mr *MockAcceptanceMockRecorder) Accept(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockAcceptance)(nil).Accept), arg0, arg1)
}

// FindByScreening mocks base method.
func (m *MockAcceptance) FindByScreening(ctx context.Context, screeningRef string) (domain.Sow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByScreening", ctx, screeningRef)
	ret0, _ := ret[0].(domain.Sow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByScreening indicates an expected call of FindByScreening.
func (mr *MockAcceptanceMockRecorder) FindByScreening(ctx, screeningRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByScreening", reflect.TypeOf((*MockAcceptance)(nil).FindByScreening), ctx, screeningRef)
}

// Settle mocks base method.
func (m *MockAcceptance) Settle(ctx context.Context, sow domain.Sow, refund bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settle", ctx, sow, refund)
	ret0, _ := ret[0].(error)
	return ret0
}

// Settle indicates an expected call of Settle.
func (mr *MockAcceptanceMockRecorder) Settle(ctx, sow, refund any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settle", reflect.TypeOf((*MockAcceptance)(nil).Settle), ctx, sow, refund)
}

// MockListenGate is a mock of ListenGate interface.
type MockListenGate struct {
	ctrl     *gomock.Controller
	recorder *MockListenGateMockRecorder
	isgomock struct{}
}

// MockListenGateMockRecorder is the mock recorder for MockListenGate.
type MockListenGateMockRecorder struct {
	mock *MockListenGate
}

// NewMockListenGate creates a new mock instance.
func NewMockListenGate(ctrl *gomock.Controller) *MockListenGate {
	mock := &MockListenGate{ctrl: ctrl}
	mock.recorder = &MockListenGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenGate) EXPECT() *MockListenGateMockRecorder {
	return m.recorder
}

// Heard mocks base method.
func (m *MockListenGate) Heard(ctx context.Context, listenerID, targetID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heard", ctx, listenerID, targetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Heard indicates an expected call of Heard.
func (mr *MockListenGateMockRecorder) Heard(ctx, listenerID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heard", reflect.TypeOf((*MockListenGate)(nil).Heard), ctx, listenerID, targetID)
}

// MockBlockList is a mock of BlockList interface.
type MockBlockList struct {
	ctrl     *gomock.Controller
	recorder *MockBlockListMockRecorder
	isgomock struct{}
}

// MockBlockListMockRecorder is the mock recorder for MockBlockList.
type MockBlockListMockRecorder struct {
	mock *MockBlockList
}

// NewMockBlockList creates a new mock instance.
func NewMockBlockList(ctrl *gomock.Controller) *MockBlockList {
	mock := &MockBlockList{ctrl: ctrl}
	mock.recorder = &MockBlockListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockList) EXPECT() *MockBlockListMockRecorder {
	return m.recorder
}

// Blocked mocks base method.
func (m *MockBlockList) Blocked(ctx context.Context, memberID, otherID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocked", ctx, memberID, otherID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocked indicates an expected call of Blocked.
func (mr *MockBlockListMockRecorder) Blocked(ctx, memberID, otherID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocked", reflect.TypeOf((*MockBlockList)(nil).Blocked), ctx, memberID, otherID)
}

// MockDeclineLock is a mock of DeclineLock interface.
type MockDeclineLock struct {
	ctrl     *gomock.Controller
	recorder *MockDeclineLockMockRecorder
	isgomock struct{}
}

// MockDeclineLockMockRecorder is the mock recorder for MockDeclineLock.
type MockDeclineLockMockRecorder struct {
	mock *MockDeclineLock
}

// NewMockDeclineLock creates a new mock instance.
func NewMockDeclineLock(ctrl *gomock.Controller) *MockDeclineLock {
	mock := &MockDeclineLock{ctrl: ctrl}
	mock.recorder = &MockDeclineLockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeclineLock) EXPECT() *MockDeclineLockMockRecorder {
	return m.recorder
}

// Locked mocks base method.
func (m *MockDeclineLock) Locked(ctx context.Context, sowerID, targetID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locked", ctx, sowerID, targetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Locked indicates an expected call of Locked.
func (mr *MockDeclineLockMockRecorder) Locked(ctx, sowerID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locked", reflect.TypeOf((*MockDeclineLock)(nil).Locked), ctx, sowerID, targetID)
}

// MockMediaOwnership is a mock of MediaOwnership interface.
type MockMediaOwnership struct {
	ctrl     *gomock.Controller
	recorder *MockMediaOwnershipMockRecorder
	isgomock struct{}
}

// MockMediaOwnershipMockRecorder is the mock recorder for MockMediaOwnership.
type MockMediaOwnershipMockRecorder struct {
	mock *MockMediaOwnership
}

// NewMockMediaOwnership creates a new mock instance.
func NewMockMediaOwnership(ctrl *gomock.Controller) *MockMediaOwnership {
	mock := &MockMediaOwnership{ctrl: ctrl}
	mock.recorder = &MockMediaOwnershipMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaOwnership) EXPECT() *MockMediaOwnershipMockRecorder {
	return m.recorder
}

// OwnedBy mocks base method.
func (m *MockMediaOwnership) OwnedBy(ctx context.Context, ownerID string, refs []string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnedBy", ctx, ownerID, refs)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnedBy indicates an expected call of OwnedBy.
func (mr *MockMediaOwnershipMockRecorder) OwnedBy(ctx, ownerID, refs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnedBy", reflect.TypeOf((*MockMediaOwnership)(nil).OwnedBy), ctx, ownerID, refs)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(namespace, value string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", namespace, value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(namespace, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), namespace, value)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
