// Code generated by MockGen. DO NOT EDIT.
// Source: internal/privacy/application/service.go
//
// Generated by this command:
//
//	mockgen -source internal/privacy/application/service.go -destination internal/privacy/application/mock_service_test.go -package application RequestRepository,LegalHoldRepository,ExportAssembler,ErasureRunner,SessionRevoker
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/internal/privacy/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestRepository is a mock of RequestRepository interface.
type MockRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockRequestRepositoryMockRecorder is the mock recorder for MockRequestRepository.
type MockRequestRepositoryMockRecorder struct {
	mock *MockRequestRepository
}

// NewMockRequestRepository creates a new mock instance.
func NewMockRequestRepository(ctrl *gomock.Controller) *MockRequestRepository {
	mock := &MockRequestRepository{ctrl: ctrl}
	mock.recorder = &MockRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestRepository) EXPECT() *MockRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRequestRepository) Create(arg0 context.Context, arg1 domain.PrivacyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRequestRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRequestRepository)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockRequestRepository) FindByID(arg0 context.Context, arg1 string) (domain.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRequestRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRequestRepository)(nil).FindByID), arg0, arg1)
}

// FindOpenByAccountAndKind mocks base method.
func (m *MockRequestRepository) FindOpenByAccountAndKind(arg0 context.Context, arg1 string, arg2 domain.Kind) (domain.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOpenByAccountAndKind", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOpenByAccountAndKind indicates an expected call of FindOpenByAccountAndKind.
func (mr *MockRequestRepositoryMockRecorder) FindOpenByAccountAndKind(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOpenByAccountAndKind", reflect.TypeOf((*MockRequestRepository)(nil).FindOpenByAccountAndKind), arg0, arg1, arg2)
}

// NextExecutable mocks base method.
func (m *MockRequestRepository) NextExecutable(arg0 context.Context, arg1 int) ([]domain.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextExecutable", arg0, arg1)
	ret0, _ := ret[0].([]domain.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextExecutable indicates an expected call of NextExecutable.
func (mr *MockRequestRepositoryMockRecorder) NextExecutable(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextExecutable", reflect.TypeOf((*MockRequestRepository)(nil).NextExecutable), arg0, arg1)
}

// Update mocks base method.
func (m *MockRequestRepository) Update(arg0 context.Context, arg1 domain.PrivacyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRequestRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRequestRepository)(nil).Update), arg0, arg1)
}

// MockLegalHoldRepository is a mock of LegalHoldRepository interface.
type MockLegalHoldRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLegalHoldRepositoryMockRecorder
	isgomock struct{}
}

// MockLegalHoldRepositoryMockRecorder is the mock recorder for MockLegalHoldRepository.
type MockLegalHoldRepositoryMockRecorder struct {
	mock *MockLegalHoldRepository
}

// NewMockLegalHoldRepository creates a new mock instance.
func NewMockLegalHoldRepository(ctrl *gomock.Controller) *MockLegalHoldRepository {
	mock := &MockLegalHoldRepository{ctrl: ctrl}
	mock.recorder = &MockLegalHoldRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLegalHoldRepository) EXPECT() *MockLegalHoldRepositoryMockRecorder {
	return m.recorder
}

// ActiveFor mocks base method.
func (m *MockLegalHoldRepository) ActiveFor(arg0 context.Context, arg1 string) (domain.LegalHold, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveFor", arg0, arg1)
	ret0, _ := ret[0].(domain.LegalHold)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveFor indicates an expected call of ActiveFor.
func (mr *MockLegalHoldRepositoryMockRecorder) ActiveFor(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveFor", reflect.TypeOf((*MockLegalHoldRepository)(nil).ActiveFor), arg0, arg1)
}

// Lift mocks base method.
func (m *MockLegalHoldRepository) Lift(arg0 context.Context, arg1 string, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lift", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lift indicates an expected call of Lift.
func (mr *MockLegalHoldRepositoryMockRecorder) Lift(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lift", reflect.TypeOf((*MockLegalHoldRepository)(nil).Lift), arg0, arg1, arg2)
}

// Place mocks base method.
func (m *MockLegalHoldRepository) Place(arg0 context.Context, arg1 domain.LegalHold) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Place", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Place indicates an expected call of Place.
func (mr *MockLegalHoldRepositoryMockRecorder) Place(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Place", reflect.TypeOf((*MockLegalHoldRepository)(nil).Place), arg0, arg1)
}

// MockExportAssembler is a mock of ExportAssembler interface.
type MockExportAssembler struct {
	ctrl     *gomock.Controller
	recorder *MockExportAssemblerMockRecorder
	isgomock struct{}
}

// MockExportAssemblerMockRecorder is the mock recorder for MockExportAssembler.
type MockExportAssemblerMockRecorder struct {
	mock *MockExportAssembler
}

// NewMockExportAssembler creates a new mock instance.
func NewMockExportAssembler(ctrl *gomock.Controller) *MockExportAssembler {
	mock := &MockExportAssembler{ctrl: ctrl}
	mock.recorder = &MockExportAssemblerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExportAssembler) EXPECT() *MockExportAssemblerMockRecorder {
	return m.recorder
}

// Assemble mocks base method.
func (m *MockExportAssembler) Assemble(ctx context.Context, requestID, accountID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assemble", ctx, requestID, accountID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assemble indicates an expected call of Assemble.
func (mr *MockExportAssemblerMockRecorder) Assemble(ctx, requestID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assemble", reflect.TypeOf((*MockExportAssembler)(nil).Assemble), ctx, requestID, accountID)
}

// MockErasureRunner is a mock of ErasureRunner interface.
type MockErasureRunner struct {
	ctrl     *gomock.Controller
	recorder *MockErasureRunnerMockRecorder
	isgomock struct{}
}

// MockErasureRunnerMockRecorder is the mock recorder for MockErasureRunner.
type MockErasureRunnerMockRecorder struct {
	mock *MockErasureRunner
}

// NewMockErasureRunner creates a new mock instance.
func NewMockErasureRunner(ctrl *gomock.Controller) *MockErasureRunner {
	mock := &MockErasureRunner{ctrl: ctrl}
	mock.recorder = &MockErasureRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErasureRunner) EXPECT() *MockErasureRunnerMockRecorder {
	return m.recorder
}

// Erase mocks base method.
func (m *MockErasureRunner) Erase(ctx context.Context, requestID, accountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Erase", ctx, requestID, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Erase indicates an expected call of Erase.
func (mr *MockErasureRunnerMockRecorder) Erase(ctx, requestID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Erase", reflect.TypeOf((*MockErasureRunner)(nil).Erase), ctx, requestID, accountID)
}

// MockSessionRevoker is a mock of SessionRevoker interface.
type MockSessionRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRevokerMockRecorder
	isgomock struct{}
}

// MockSessionRevokerMockRecorder is the mock recorder for MockSessionRevoker.
type MockSessionRevokerMockRecorder struct {
	mock *MockSessionRevoker
}

// NewMockSessionRevoker creates a new mock instance.
func NewMockSessionRevoker(ctrl *gomock.Controller) *MockSessionRevoker {
	mock := &MockSessionRevoker{ctrl: ctrl}
	mock.recorder = &MockSessionRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRevoker) EXPECT() *MockSessionRevokerMockRecorder {
	return m.recorder
}

// RevokeMemberSessions mocks base method.
func (m *MockSessionRevoker) RevokeMemberSessions(ctx context.Context, memberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeMemberSessions", ctx, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeMemberSessions indicates an expected call of RevokeMemberSessions.
func (mr *MockSessionRevokerMockRecorder) RevokeMemberSessions(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeMemberSessions", reflect.TypeOf((*MockSessionRevoker)(nil).RevokeMemberSessions), ctx, memberID)
}
