// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/seed/listening/application/listening.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/seed/listening/application/listening.go -destination services/api/internal/seed/listening/application/mock_listening_test.go -package application ListeningRepository
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/seed/listening/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockListeningRepository is a mock of ListeningRepository interface.
type MockListeningRepository struct {
	ctrl     *gomock.Controller
	recorder *MockListeningRepositoryMockRecorder
	isgomock struct{}
}

// MockListeningRepositoryMockRecorder is the mock recorder for MockListeningRepository.
type MockListeningRepositoryMockRecorder struct {
	mock *MockListeningRepository
}

// NewMockListeningRepository creates a new mock instance.
func NewMockListeningRepository(ctrl *gomock.Controller) *MockListeningRepository {
	mock := &MockListeningRepository{ctrl: ctrl}
	mock.recorder = &MockListeningRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListeningRepository) EXPECT() *MockListeningRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockListeningRepository) Find(arg0 context.Context, arg1, arg2 string) (domain.Playback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Playback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockListeningRepositoryMockRecorder) Find(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockListeningRepository)(nil).Find), arg0, arg1, arg2)
}

// Save mocks base method.
func (m *MockListeningRepository) Save(arg0 context.Context, arg1 domain.Playback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockListeningRepositoryMockRecorder) Save(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockListeningRepository)(nil).Save), arg0, arg1)
}
