// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/commerce/affiliate/application/ports.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/commerce/affiliate/application/ports.go -destination services/api/internal/commerce/affiliate/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/commerce/affiliate/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(ctx context.Context, affiliate domain.Affiliate, expected uint64, commandID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, affiliate, expected, commandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(ctx, affiliate, expected, commandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), ctx, affiliate, expected, commandID)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Affiliate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// FindByCode mocks base method.
func (m *MockRepository) FindByCode(arg0 context.Context, arg1 string) (domain.Affiliate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCode", arg0, arg1)
	ret0, _ := ret[0].(domain.Affiliate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCode indicates an expected call of FindByCode.
func (mr *MockRepositoryMockRecorder) FindByCode(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCode", reflect.TypeOf((*MockRepository)(nil).FindByCode), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(arg0 context.Context, arg1 string) (domain.Affiliate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Affiliate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), arg0, arg1)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, limit int) ([]domain.Affiliate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]domain.Affiliate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, limit)
}

// MockReferrals is a mock of Referrals interface.
type MockReferrals struct {
	ctrl     *gomock.Controller
	recorder *MockReferralsMockRecorder
	isgomock struct{}
}

// MockReferralsMockRecorder is the mock recorder for MockReferrals.
type MockReferralsMockRecorder struct {
	mock *MockReferrals
}

// NewMockReferrals creates a new mock instance.
func NewMockReferrals(ctrl *gomock.Controller) *MockReferrals {
	mock := &MockReferrals{ctrl: ctrl}
	mock.recorder = &MockReferralsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReferrals) EXPECT() *MockReferralsMockRecorder {
	return m.recorder
}

// DueForQualification mocks base method.
func (m *MockReferrals) DueForQualification(ctx context.Context, at time.Time, limit int) ([]Referral, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DueForQualification", ctx, at, limit)
	ret0, _ := ret[0].([]Referral)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DueForQualification indicates an expected call of DueForQualification.
func (mr *MockReferralsMockRecorder) DueForQualification(ctx, at, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DueForQualification", reflect.TypeOf((*MockReferrals)(nil).DueForQualification), ctx, at, limit)
}

// Find mocks base method.
func (m *MockReferrals) Find(ctx context.Context, memberKey string) (Referral, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, memberKey)
	ret0, _ := ret[0].(Referral)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockReferralsMockRecorder) Find(ctx, memberKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockReferrals)(nil).Find), ctx, memberKey)
}

// MarkSettled mocks base method.
func (m *MockReferrals) MarkSettled(ctx context.Context, memberKey, outcome string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSettled", ctx, memberKey, outcome)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSettled indicates an expected call of MarkSettled.
func (mr *MockReferralsMockRecorder) MarkSettled(ctx, memberKey, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSettled", reflect.TypeOf((*MockReferrals)(nil).MarkSettled), ctx, memberKey, outcome)
}

// Record mocks base method.
func (m *MockReferrals) Record(arg0 context.Context, arg1 Referral) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockReferralsMockRecorder) Record(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockReferrals)(nil).Record), arg0, arg1)
}

// MockQualification is a mock of Qualification interface.
type MockQualification struct {
	ctrl     *gomock.Controller
	recorder *MockQualificationMockRecorder
	isgomock struct{}
}

// MockQualificationMockRecorder is the mock recorder for MockQualification.
type MockQualificationMockRecorder struct {
	mock *MockQualification
}

// NewMockQualification creates a new mock instance.
func NewMockQualification(ctrl *gomock.Controller) *MockQualification {
	mock := &MockQualification{ctrl: ctrl}
	mock.recorder = &MockQualificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQualification) EXPECT() *MockQualificationMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *MockQualification) Clean(ctx context.Context, memberKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", ctx, memberKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockQualificationMockRecorder) Clean(ctx, memberKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockQualification)(nil).Clean), ctx, memberKey)
}

// Verified mocks base method.
func (m *MockQualification) Verified(ctx context.Context, memberKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verified", ctx, memberKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verified indicates an expected call of Verified.
func (mr *MockQualificationMockRecorder) Verified(ctx, memberKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verified", reflect.TypeOf((*MockQualification)(nil).Verified), ctx, memberKey)
}

// MockLedger is a mock of Ledger interface.
type MockLedger struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerMockRecorder
	isgomock struct{}
}

// MockLedgerMockRecorder is the mock recorder for MockLedger.
type MockLedgerMockRecorder struct {
	mock *MockLedger
}

// NewMockLedger creates a new mock instance.
func NewMockLedger(ctrl *gomock.Controller) *MockLedger {
	mock := &MockLedger{ctrl: ctrl}
	mock.recorder = &MockLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedger) EXPECT() *MockLedgerMockRecorder {
	return m.recorder
}

// RecordAccrual mocks base method.
func (m *MockLedger) RecordAccrual(ctx context.Context, reference string, minor int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordAccrual", ctx, reference, minor, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordAccrual indicates an expected call of RecordAccrual.
func (mr *MockLedgerMockRecorder) RecordAccrual(ctx, reference, minor, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordAccrual", reflect.TypeOf((*MockLedger)(nil).RecordAccrual), ctx, reference, minor, at)
}

// RecordClawback mocks base method.
func (m *MockLedger) RecordClawback(ctx context.Context, reference string, minor int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClawback", ctx, reference, minor, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClawback indicates an expected call of RecordClawback.
func (mr *MockLedgerMockRecorder) RecordClawback(ctx, reference, minor, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClawback", reflect.TypeOf((*MockLedger)(nil).RecordClawback), ctx, reference, minor, at)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// MemberKey mocks base method.
func (m *MockKeyer) MemberKey(memberID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberKey", memberID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberKey indicates an expected call of MemberKey.
func (mr *MockKeyerMockRecorder) MemberKey(memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberKey", reflect.TypeOf((*MockKeyer)(nil).MemberKey), memberID)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
