// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/commerce/affiliate/application/payout.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/commerce/affiliate/application/payout.go -destination services/api/internal/commerce/affiliate/application/mock_payout_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/commerce/affiliate/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPayouts is a mock of Payouts interface.
type MockPayouts struct {
	ctrl     *gomock.Controller
	recorder *MockPayoutsMockRecorder
	isgomock struct{}
}

// MockPayoutsMockRecorder is the mock recorder for MockPayouts.
type MockPayoutsMockRecorder struct {
	mock *MockPayouts
}

// NewMockPayouts creates a new mock instance.
func NewMockPayouts(ctrl *gomock.Controller) *MockPayouts {
	mock := &MockPayouts{ctrl: ctrl}
	mock.recorder = &MockPayoutsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayouts) EXPECT() *MockPayoutsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPayouts) Create(arg0 context.Context, arg1 domain.Payout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPayoutsMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPayouts)(nil).Create), arg0, arg1)
}

// Find mocks base method.
func (m *MockPayouts) Find(ctx context.Context, id string) (domain.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(domain.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockPayoutsMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockPayouts)(nil).Find), ctx, id)
}

// Pending mocks base method.
func (m *MockPayouts) Pending(ctx context.Context, limit int) ([]domain.Payout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pending", ctx, limit)
	ret0, _ := ret[0].([]domain.Payout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pending indicates an expected call of Pending.
func (mr *MockPayoutsMockRecorder) Pending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pending", reflect.TypeOf((*MockPayouts)(nil).Pending), ctx, limit)
}

// Save mocks base method.
func (m *MockPayouts) Save(ctx context.Context, payout domain.Payout, expected domain.PayoutStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, payout, expected)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPayoutsMockRecorder) Save(ctx, payout, expected any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPayouts)(nil).Save), ctx, payout, expected)
}

// MockTransfers is a mock of Transfers interface.
type MockTransfers struct {
	ctrl     *gomock.Controller
	recorder *MockTransfersMockRecorder
	isgomock struct{}
}

// MockTransfersMockRecorder is the mock recorder for MockTransfers.
type MockTransfersMockRecorder struct {
	mock *MockTransfers
}

// NewMockTransfers creates a new mock instance.
func NewMockTransfers(ctrl *gomock.Controller) *MockTransfers {
	mock := &MockTransfers{ctrl: ctrl}
	mock.recorder = &MockTransfersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransfers) EXPECT() *MockTransfersMockRecorder {
	return m.recorder
}

// CreateRecipient mocks base method.
func (m *MockTransfers) CreateRecipient(ctx context.Context, name, phone, network string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecipient", ctx, name, phone, network)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecipient indicates an expected call of CreateRecipient.
func (mr *MockTransfersMockRecorder) CreateRecipient(ctx, name, phone, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecipient", reflect.TypeOf((*MockTransfers)(nil).CreateRecipient), ctx, name, phone, network)
}

// Transfer mocks base method.
func (m *MockTransfers) Transfer(ctx context.Context, recipientCode, reference, reason string, amountPesewas int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", ctx, recipientCode, reference, reason, amountPesewas)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockTransfersMockRecorder) Transfer(ctx, recipientCode, reference, reason, amountPesewas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockTransfers)(nil).Transfer), ctx, recipientCode, reference, reason, amountPesewas)
}

// MockPayoutLedger is a mock of PayoutLedger interface.
type MockPayoutLedger struct {
	ctrl     *gomock.Controller
	recorder *MockPayoutLedgerMockRecorder
	isgomock struct{}
}

// MockPayoutLedgerMockRecorder is the mock recorder for MockPayoutLedger.
type MockPayoutLedgerMockRecorder struct {
	mock *MockPayoutLedger
}

// NewMockPayoutLedger creates a new mock instance.
func NewMockPayoutLedger(ctrl *gomock.Controller) *MockPayoutLedger {
	mock := &MockPayoutLedger{ctrl: ctrl}
	mock.recorder = &MockPayoutLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayoutLedger) EXPECT() *MockPayoutLedgerMockRecorder {
	return m.recorder
}

// RecordPayout mocks base method.
func (m *MockPayoutLedger) RecordPayout(ctx context.Context, reference string, grossMinor, withheldMinor, netMinor int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPayout", ctx, reference, grossMinor, withheldMinor, netMinor, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPayout indicates an expected call of RecordPayout.
func (mr *MockPayoutLedgerMockRecorder) RecordPayout(ctx, reference, grossMinor, withheldMinor, netMinor, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPayout", reflect.TypeOf((*MockPayoutLedger)(nil).RecordPayout), ctx, reference, grossMinor, withheldMinor, netMinor, at)
}
