// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/identity/application/registration.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/identity/application/registration.go -destination services/api/internal/identity/application/mock_registration_test.go -package application OtpChallengeRepository,AccountRepository,OtpSender
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/identity/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOtpChallengeRepository is a mock of OtpChallengeRepository interface.
type MockOtpChallengeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOtpChallengeRepositoryMockRecorder
	isgomock struct{}
}

// MockOtpChallengeRepositoryMockRecorder is the mock recorder for MockOtpChallengeRepository.
type MockOtpChallengeRepositoryMockRecorder struct {
	mock *MockOtpChallengeRepository
}

// NewMockOtpChallengeRepository creates a new mock instance.
func NewMockOtpChallengeRepository(ctrl *gomock.Controller) *MockOtpChallengeRepository {
	mock := &MockOtpChallengeRepository{ctrl: ctrl}
	mock.recorder = &MockOtpChallengeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOtpChallengeRepository) EXPECT() *MockOtpChallengeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOtpChallengeRepository) Create(arg0 context.Context, arg1 domain.OtpChallenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOtpChallengeRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOtpChallengeRepository)(nil).Create), arg0, arg1)
}

// LatestByContact mocks base method.
func (m *MockOtpChallengeRepository) LatestByContact(arg0 context.Context, arg1 domain.Contact) (domain.OtpChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestByContact", arg0, arg1)
	ret0, _ := ret[0].(domain.OtpChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestByContact indicates an expected call of LatestByContact.
func (mr *MockOtpChallengeRepositoryMockRecorder) LatestByContact(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestByContact", reflect.TypeOf((*MockOtpChallengeRepository)(nil).LatestByContact), arg0, arg1)
}

// Update mocks base method.
func (m *MockOtpChallengeRepository) Update(arg0 context.Context, arg1 domain.OtpChallenge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOtpChallengeRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOtpChallengeRepository)(nil).Update), arg0, arg1)
}

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountRepository) Create(arg0 context.Context, arg1 domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountRepository)(nil).Create), arg0, arg1)
}

// FindByContact mocks base method.
func (m *MockAccountRepository) FindByContact(arg0 context.Context, arg1 domain.Contact) (domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContact", arg0, arg1)
	ret0, _ := ret[0].(domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContact indicates an expected call of FindByContact.
func (mr *MockAccountRepositoryMockRecorder) FindByContact(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContact", reflect.TypeOf((*MockAccountRepository)(nil).FindByContact), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockAccountRepository) FindByID(arg0 context.Context, arg1 string) (domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAccountRepositoryMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAccountRepository)(nil).FindByID), arg0, arg1)
}

// List mocks base method.
func (m *MockAccountRepository) List(arg0 context.Context, arg1 int) ([]domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccountRepositoryMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccountRepository)(nil).List), arg0, arg1)
}

// ListSuspendedExpired mocks base method.
func (m *MockAccountRepository) ListSuspendedExpired(arg0 context.Context, arg1 time.Time, arg2 int) ([]domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSuspendedExpired", arg0, arg1, arg2)
	ret0, _ := ret[0].([]domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSuspendedExpired indicates an expected call of ListSuspendedExpired.
func (mr *MockAccountRepositoryMockRecorder) ListSuspendedExpired(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSuspendedExpired", reflect.TypeOf((*MockAccountRepository)(nil).ListSuspendedExpired), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockAccountRepository) Update(arg0 context.Context, arg1 domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountRepository)(nil).Update), arg0, arg1)
}

// UpdateWithAudit mocks base method.
func (m *MockAccountRepository) UpdateWithAudit(arg0 context.Context, arg1 domain.Account, arg2 domain.TierTransition) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithAudit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithAudit indicates an expected call of UpdateWithAudit.
func (mr *MockAccountRepositoryMockRecorder) UpdateWithAudit(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithAudit", reflect.TypeOf((*MockAccountRepository)(nil).UpdateWithAudit), arg0, arg1, arg2)
}

// MockOtpSender is a mock of OtpSender interface.
type MockOtpSender struct {
	ctrl     *gomock.Controller
	recorder *MockOtpSenderMockRecorder
	isgomock struct{}
}

// MockOtpSenderMockRecorder is the mock recorder for MockOtpSender.
type MockOtpSenderMockRecorder struct {
	mock *MockOtpSender
}

// NewMockOtpSender creates a new mock instance.
func NewMockOtpSender(ctrl *gomock.Controller) *MockOtpSender {
	mock := &MockOtpSender{ctrl: ctrl}
	mock.recorder = &MockOtpSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOtpSender) EXPECT() *MockOtpSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockOtpSender) Send(ctx context.Context, contact domain.Contact, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, contact, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockOtpSenderMockRecorder) Send(ctx, contact, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockOtpSender)(nil).Send), ctx, contact, code)
}
