// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/whatsapp/application/channel.go
//
// Generated by this command:
//
//	mockgen -source internal/notifications/whatsapp/application/channel.go -destination internal/notifications/whatsapp/application/mock_channel_test.go -package application Sender,DeliveryLog,PreferenceDecider
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/internal/notifications/domain"
	domain0 "github.com/stanleyHayes/obiara/internal/notifications/whatsapp/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender) Send(arg0 context.Context, arg1 domain0.Message) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), arg0, arg1)
}

// MockDeliveryLog is a mock of DeliveryLog interface.
type MockDeliveryLog struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryLogMockRecorder
	isgomock struct{}
}

// MockDeliveryLogMockRecorder is the mock recorder for MockDeliveryLog.
type MockDeliveryLogMockRecorder struct {
	mock *MockDeliveryLog
}

// NewMockDeliveryLog creates a new mock instance.
func NewMockDeliveryLog(ctrl *gomock.Controller) *MockDeliveryLog {
	mock := &MockDeliveryLog{ctrl: ctrl}
	mock.recorder = &MockDeliveryLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryLog) EXPECT() *MockDeliveryLogMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockDeliveryLog) Record(ctx context.Context, entry DeliveryEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockDeliveryLogMockRecorder) Record(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockDeliveryLog)(nil).Record), ctx, entry)
}

// MockPreferenceDecider is a mock of PreferenceDecider interface.
type MockPreferenceDecider struct {
	ctrl     *gomock.Controller
	recorder *MockPreferenceDeciderMockRecorder
	isgomock struct{}
}

// MockPreferenceDeciderMockRecorder is the mock recorder for MockPreferenceDecider.
type MockPreferenceDeciderMockRecorder struct {
	mock *MockPreferenceDecider
}

// NewMockPreferenceDecider creates a new mock instance.
func NewMockPreferenceDecider(ctrl *gomock.Controller) *MockPreferenceDecider {
	mock := &MockPreferenceDecider{ctrl: ctrl}
	mock.recorder = &MockPreferenceDeciderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreferenceDecider) EXPECT() *MockPreferenceDeciderMockRecorder {
	return m.recorder
}

// Decide mocks base method.
func (m *MockPreferenceDecider) Decide(ctx context.Context, memberID string, category domain.Category) (domain.Decision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decide", ctx, memberID, category)
	ret0, _ := ret[0].(domain.Decision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decide indicates an expected call of Decide.
func (mr *MockPreferenceDeciderMockRecorder) Decide(ctx, memberID, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decide", reflect.TypeOf((*MockPreferenceDecider)(nil).Decide), ctx, memberID, category)
}
