// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/commerce/sponsorship/application/service.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/commerce/sponsorship/application/service.go -destination services/api/internal/commerce/sponsorship/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/services/api/internal/commerce/sponsorship/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockRepository) Append(ctx context.Context, fund domain.Fund, expected uint64, commandID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, fund, expected, commandID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockRepositoryMockRecorder) Append(ctx, fund, expected, commandID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockRepository)(nil).Append), ctx, fund, expected, commandID)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 context.Context, arg1 domain.Fund) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0, arg1)
}

// FindByOrganization mocks base method.
func (m *MockRepository) FindByOrganization(ctx context.Context, organizationID string) (domain.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrganization", ctx, organizationID)
	ret0, _ := ret[0].(domain.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrganization indicates an expected call of FindByOrganization.
func (mr *MockRepositoryMockRecorder) FindByOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrganization", reflect.TypeOf((*MockRepository)(nil).FindByOrganization), ctx, organizationID)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, limit int) ([]domain.Fund, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]domain.Fund)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, limit)
}

// MockIssuers is a mock of Issuers interface.
type MockIssuers struct {
	ctrl     *gomock.Controller
	recorder *MockIssuersMockRecorder
	isgomock struct{}
}

// MockIssuersMockRecorder is the mock recorder for MockIssuers.
type MockIssuersMockRecorder struct {
	mock *MockIssuers
}

// NewMockIssuers creates a new mock instance.
func NewMockIssuers(ctrl *gomock.Controller) *MockIssuers {
	mock := &MockIssuers{ctrl: ctrl}
	mock.recorder = &MockIssuersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssuers) EXPECT() *MockIssuersMockRecorder {
	return m.recorder
}

// Issuing mocks base method.
func (m *MockIssuers) Issuing(ctx context.Context, organizationID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issuing", ctx, organizationID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issuing indicates an expected call of Issuing.
func (mr *MockIssuersMockRecorder) Issuing(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issuing", reflect.TypeOf((*MockIssuers)(nil).Issuing), ctx, organizationID)
}

// MockLedger is a mock of Ledger interface.
type MockLedger struct {
	ctrl     *gomock.Controller
	recorder *MockLedgerMockRecorder
	isgomock struct{}
}

// MockLedgerMockRecorder is the mock recorder for MockLedger.
type MockLedgerMockRecorder struct {
	mock *MockLedger
}

// NewMockLedger creates a new mock instance.
func NewMockLedger(ctrl *gomock.Controller) *MockLedger {
	mock := &MockLedger{ctrl: ctrl}
	mock.recorder = &MockLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLedger) EXPECT() *MockLedgerMockRecorder {
	return m.recorder
}

// RecordDeposit mocks base method.
func (m *MockLedger) RecordDeposit(ctx context.Context, reference string, minor int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordDeposit", ctx, reference, minor, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordDeposit indicates an expected call of RecordDeposit.
func (mr *MockLedgerMockRecorder) RecordDeposit(ctx, reference, minor, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDeposit", reflect.TypeOf((*MockLedger)(nil).RecordDeposit), ctx, reference, minor, at)
}

// RecordDraw mocks base method.
func (m *MockLedger) RecordDraw(ctx context.Context, reference string, minor int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordDraw", ctx, reference, minor, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordDraw indicates an expected call of RecordDraw.
func (mr *MockLedgerMockRecorder) RecordDraw(ctx, reference, minor, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDraw", reflect.TypeOf((*MockLedger)(nil).RecordDraw), ctx, reference, minor, at)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
