// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mock_ports_test.go -package=application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/circle/workflow/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateInvite mocks base method.
func (m *MockRepository) CreateInvite(arg0 context.Context, arg1 domain.Invite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockRepositoryMockRecorder) CreateInvite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockRepository)(nil).CreateInvite), arg0, arg1)
}

// CreateRequest mocks base method.
func (m *MockRepository) CreateRequest(arg0 context.Context, arg1 domain.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRequest indicates an expected call of CreateRequest.
func (mr *MockRepositoryMockRecorder) CreateRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequest", reflect.TypeOf((*MockRepository)(nil).CreateRequest), arg0, arg1)
}

// FindInviteByCommand mocks base method.
func (m *MockRepository) FindInviteByCommand(arg0 context.Context, arg1 string) (domain.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInviteByCommand", arg0, arg1)
	ret0, _ := ret[0].(domain.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInviteByCommand indicates an expected call of FindInviteByCommand.
func (mr *MockRepositoryMockRecorder) FindInviteByCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInviteByCommand", reflect.TypeOf((*MockRepository)(nil).FindInviteByCommand), arg0, arg1)
}

// FindInviteByDigest mocks base method.
func (m *MockRepository) FindInviteByDigest(arg0 context.Context, arg1 string) (domain.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInviteByDigest", arg0, arg1)
	ret0, _ := ret[0].(domain.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInviteByDigest indicates an expected call of FindInviteByDigest.
func (mr *MockRepositoryMockRecorder) FindInviteByDigest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInviteByDigest", reflect.TypeOf((*MockRepository)(nil).FindInviteByDigest), arg0, arg1)
}

// FindRequest mocks base method.
func (m *MockRepository) FindRequest(arg0 context.Context, arg1 string) (domain.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRequest", arg0, arg1)
	ret0, _ := ret[0].(domain.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRequest indicates an expected call of FindRequest.
func (mr *MockRepositoryMockRecorder) FindRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRequest", reflect.TypeOf((*MockRepository)(nil).FindRequest), arg0, arg1)
}

// FindRequestByCommand mocks base method.
func (m *MockRepository) FindRequestByCommand(arg0 context.Context, arg1 string) (domain.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRequestByCommand", arg0, arg1)
	ret0, _ := ret[0].(domain.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRequestByCommand indicates an expected call of FindRequestByCommand.
func (mr *MockRepositoryMockRecorder) FindRequestByCommand(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRequestByCommand", reflect.TypeOf((*MockRepository)(nil).FindRequestByCommand), arg0, arg1)
}

// Redeem mocks base method.
func (m *MockRepository) Redeem(arg0 context.Context, arg1 domain.Invite, arg2 domain.Request, arg3 uint64, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redeem", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redeem indicates an expected call of Redeem.
func (mr *MockRepositoryMockRecorder) Redeem(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeem", reflect.TypeOf((*MockRepository)(nil).Redeem), arg0, arg1, arg2, arg3, arg4)
}

// SaveRequest mocks base method.
func (m *MockRepository) SaveRequest(arg0 context.Context, arg1 domain.Request, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRequest", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRequest indicates an expected call of SaveRequest.
func (mr *MockRepositoryMockRecorder) SaveRequest(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRequest", reflect.TypeOf((*MockRepository)(nil).SaveRequest), arg0, arg1, arg2, arg3)
}

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
	isgomock struct{}
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// Require mocks base method.
func (m *MockAuthorizer) Require(ctx context.Context, actorID, circleID, action, memberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Require", ctx, actorID, circleID, action, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Require indicates an expected call of Require.
func (mr *MockAuthorizerMockRecorder) Require(ctx, actorID, circleID, action, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Require", reflect.TypeOf((*MockAuthorizer)(nil).Require), ctx, actorID, circleID, action, memberID)
}

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// Digest mocks base method.
func (m *MockTokenIssuer) Digest(raw string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Digest", raw)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Digest indicates an expected call of Digest.
func (mr *MockTokenIssuerMockRecorder) Digest(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Digest", reflect.TypeOf((*MockTokenIssuer)(nil).Digest), raw)
}

// NewToken mocks base method.
func (m *MockTokenIssuer) NewToken() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NewToken indicates an expected call of NewToken.
func (mr *MockTokenIssuerMockRecorder) NewToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewToken", reflect.TypeOf((*MockTokenIssuer)(nil).NewToken))
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID))
}
