// Code generated by MockGen. DO NOT EDIT.
// Source: services/api/internal/introduction/application/ports.go
//
// Generated by this command:
//
//	mockgen -source services/api/internal/introduction/application/ports.go -destination services/api/internal/introduction/application/mock_ports_test.go -package application
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"

	domain "github.com/stanleyHayes/obiara/services/api/internal/introduction/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStore) Create(arg0 context.Context, arg1 domain.Introduction) (domain.Introduction, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(domain.Introduction)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockStoreMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStore)(nil).Create), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockStore) FindByID(arg0 context.Context, arg1 string) (domain.Introduction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(domain.Introduction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockStoreMockRecorder) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockStore)(nil).FindByID), arg0, arg1)
}

// PromptsRecorded mocks base method.
func (m *MockStore) PromptsRecorded(arg0 context.Context, arg1 string) ([]domain.Prompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptsRecorded", arg0, arg1)
	ret0, _ := ret[0].([]domain.Prompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptsRecorded indicates an expected call of PromptsRecorded.
func (mr *MockStoreMockRecorder) PromptsRecorded(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptsRecorded", reflect.TypeOf((*MockStore)(nil).PromptsRecorded), arg0, arg1)
}

// Update mocks base method.
func (m *MockStore) Update(arg0 context.Context, arg1 domain.Introduction, arg2 uint64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStoreMockRecorder) Update(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStore)(nil).Update), arg0, arg1, arg2, arg3)
}

// MockLadder is a mock of Ladder interface.
type MockLadder struct {
	ctrl     *gomock.Controller
	recorder *MockLadderMockRecorder
	isgomock struct{}
}

// MockLadderMockRecorder is the mock recorder for MockLadder.
type MockLadderMockRecorder struct {
	mock *MockLadder
}

// NewMockLadder creates a new mock instance.
func NewMockLadder(ctrl *gomock.Controller) *MockLadder {
	mock := &MockLadder{ctrl: ctrl}
	mock.recorder = &MockLadderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLadder) EXPECT() *MockLadderMockRecorder {
	return m.recorder
}

// SowingEarned mocks base method.
func (m *MockLadder) SowingEarned(ctx context.Context, memberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SowingEarned", ctx, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SowingEarned indicates an expected call of SowingEarned.
func (mr *MockLadderMockRecorder) SowingEarned(ctx, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SowingEarned", reflect.TypeOf((*MockLadder)(nil).SowingEarned), ctx, memberID)
}

// MockConsentGate is a mock of ConsentGate interface.
type MockConsentGate struct {
	ctrl     *gomock.Controller
	recorder *MockConsentGateMockRecorder
	isgomock struct{}
}

// MockConsentGateMockRecorder is the mock recorder for MockConsentGate.
type MockConsentGateMockRecorder struct {
	mock *MockConsentGate
}

// NewMockConsentGate creates a new mock instance.
func NewMockConsentGate(ctrl *gomock.Controller) *MockConsentGate {
	mock := &MockConsentGate{ctrl: ctrl}
	mock.recorder = &MockConsentGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentGate) EXPECT() *MockConsentGateMockRecorder {
	return m.recorder
}

// Effective mocks base method.
func (m *MockConsentGate) Effective(arg0 context.Context, arg1, arg2 string, arg3 uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Effective", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Effective indicates an expected call of Effective.
func (mr *MockConsentGateMockRecorder) Effective(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Effective", reflect.TypeOf((*MockConsentGate)(nil).Effective), arg0, arg1, arg2, arg3)
}

// MockMediaManager is a mock of MediaManager interface.
type MockMediaManager struct {
	ctrl     *gomock.Controller
	recorder *MockMediaManagerMockRecorder
	isgomock struct{}
}

// MockMediaManagerMockRecorder is the mock recorder for MockMediaManager.
type MockMediaManagerMockRecorder struct {
	mock *MockMediaManager
}

// NewMockMediaManager creates a new mock instance.
func NewMockMediaManager(ctrl *gomock.Controller) *MockMediaManager {
	mock := &MockMediaManager{ctrl: ctrl}
	mock.recorder = &MockMediaManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaManager) EXPECT() *MockMediaManagerMockRecorder {
	return m.recorder
}

// AuthorizeUpload mocks base method.
func (m *MockMediaManager) AuthorizeUpload(arg0 context.Context, arg1, arg2, arg3 string) (UploadAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeUpload", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(UploadAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeUpload indicates an expected call of AuthorizeUpload.
func (mr *MockMediaManagerMockRecorder) AuthorizeUpload(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeUpload", reflect.TypeOf((*MockMediaManager)(nil).AuthorizeUpload), arg0, arg1, arg2, arg3)
}

// Delete mocks base method.
func (m *MockMediaManager) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaManagerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaManager)(nil).Delete), arg0, arg1)
}

// Inspect mocks base method.
func (m *MockMediaManager) Inspect(arg0 context.Context, arg1 string) (domain.MediaRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", arg0, arg1)
	ret0, _ := ret[0].(domain.MediaRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockMediaManagerMockRecorder) Inspect(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockMediaManager)(nil).Inspect), arg0, arg1)
}

// MockTranscriber is a mock of Transcriber interface.
type MockTranscriber struct {
	ctrl     *gomock.Controller
	recorder *MockTranscriberMockRecorder
	isgomock struct{}
}

// MockTranscriberMockRecorder is the mock recorder for MockTranscriber.
type MockTranscriberMockRecorder struct {
	mock *MockTranscriber
}

// NewMockTranscriber creates a new mock instance.
func NewMockTranscriber(ctrl *gomock.Controller) *MockTranscriber {
	mock := &MockTranscriber{ctrl: ctrl}
	mock.recorder = &MockTranscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranscriber) EXPECT() *MockTranscriberMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockTranscriber) Cancel(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockTranscriberMockRecorder) Cancel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockTranscriber)(nil).Cancel), arg0, arg1)
}

// Delete mocks base method.
func (m *MockTranscriber) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTranscriberMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTranscriber)(nil).Delete), arg0, arg1)
}

// Transcribe mocks base method.
func (m *MockTranscriber) Transcribe(arg0 context.Context, arg1 TranscriptionRequest) (TranscriptionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", arg0, arg1)
	ret0, _ := ret[0].(TranscriptionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockTranscriberMockRecorder) Transcribe(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockTranscriber)(nil).Transcribe), arg0, arg1)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockKeyer) Key(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key), arg0)
}

// MockIDSource is a mock of IDSource interface.
type MockIDSource struct {
	ctrl     *gomock.Controller
	recorder *MockIDSourceMockRecorder
	isgomock struct{}
}

// MockIDSourceMockRecorder is the mock recorder for MockIDSource.
type MockIDSourceMockRecorder struct {
	mock *MockIDSource
}

// NewMockIDSource creates a new mock instance.
func NewMockIDSource(ctrl *gomock.Controller) *MockIDSource {
	mock := &MockIDSource{ctrl: ctrl}
	mock.recorder = &MockIDSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDSource) EXPECT() *MockIDSourceMockRecorder {
	return m.recorder
}

// NewID mocks base method.
func (m *MockIDSource) NewID(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewID", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// NewID indicates an expected call of NewID.
func (mr *MockIDSourceMockRecorder) NewID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewID", reflect.TypeOf((*MockIDSource)(nil).NewID), arg0)
}
