// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/email/application/service.go
//
// Generated by this command:
//
//	mockgen -source internal/notifications/email/application/service.go -destination internal/notifications/email/application/mock_service_test.go -package application Sender,DeliveryLog
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/stanleyHayes/obiara/internal/notifications/email/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender) Send(arg0 context.Context, arg1 domain.Message) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), arg0, arg1)
}

// MockDeliveryLog is a mock of DeliveryLog interface.
type MockDeliveryLog struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryLogMockRecorder
	isgomock struct{}
}

// MockDeliveryLogMockRecorder is the mock recorder for MockDeliveryLog.
type MockDeliveryLogMockRecorder struct {
	mock *MockDeliveryLog
}

// NewMockDeliveryLog creates a new mock instance.
func NewMockDeliveryLog(ctrl *gomock.Controller) *MockDeliveryLog {
	mock := &MockDeliveryLog{ctrl: ctrl}
	mock.recorder = &MockDeliveryLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryLog) EXPECT() *MockDeliveryLogMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockDeliveryLog) Record(ctx context.Context, entry DeliveryEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockDeliveryLogMockRecorder) Record(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockDeliveryLog)(nil).Record), ctx, entry)
}

// UpdateStatus mocks base method.
func (m *MockDeliveryLog) UpdateStatus(ctx context.Context, providerRef, status string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, providerRef, status, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDeliveryLogMockRecorder) UpdateStatus(ctx, providerRef, status, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDeliveryLog)(nil).UpdateStatus), ctx, providerRef, status, at)
}
